(function(root){
'use strict';
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]!==b[j-1]));prev=old;}}return row[b.length];}
function dictionary(pokemon){const map=new Map();for(const p of pokemon){const visible=p.speciesName.replace(/\s*\([^)]*\)/g,'').replace(/\s*Shadow$/i,'');for(const name of [p.speciesName,visible,p.speciesId.replace(/_/g,' ')]){const key=normalize(name);if(!map.has(key))map.set(key,[]);if(!map.get(key).some(x=>x.speciesId===p.speciesId))map.get(key).push(p);}}return map;}
function match(text,dict){const key=normalize(text.replace(/\bCP\s*\d+/gi,''));if(key.length<3)return null;let candidates=dict.get(key),quality='exact';if(!candidates){let best=99;for(const [name,items] of dict){if(Math.abs(name.length-key.length)>1)continue;const d=distance(key,name);if(d<best){best=d;candidates=items;}else if(d===best)candidates=[...candidates,...items];}if(best>1||key.length<5)return null;quality='suggestion';}candidates=[...new Map(candidates.map(p=>[p.speciesId,p])).values()];return {label:text.trim(),candidates:candidates.map(p=>({id:p.speciesId,name:p.speciesName,types:p.types,dex:p.dex})),key:normalize(candidates[0].speciesName.replace(/\s*\([^)]*\)/g,'').replace(/\s*Shadow$/i,'')),quality,id:quality==='exact'&&candidates.length===1?candidates[0].speciesId:''};}
function outcome(text){const key=normalize(text);if(key.length>=6&&key.length<=11&&distance(key,'youwin')<=1)return 'Win';if(key.length>=9&&key.length<=13&&distance(key,'goodeffort')<=1)return 'Loss';if(/\byou\s+win\b/i.test(text))return 'Win';if(/\bgood\s+effort\b|\byou\s+lose\b/i.test(text))return 'Loss';if(/\btie\b/i.test(text))return 'Tie';return null;}
class Tracker{
 constructor(){this.battles=[];this.current=null;this.pending={};this.lastSeen=-Infinity;this.lastOutcome=-Infinity;this.resultPending=null;}
 start(t){this.current={id:globalThis.crypto?.randomUUID?.()||String(Math.random()),start:t,end:t,my:[],opponent:[],events:[],result:'Unknown',flags:['Confirm battle boundary and lead'],reviewed:false,leadConfirmed:false};}
 close(t,reason){if(!this.current)return;this.current.end=t;if(reason)this.current.flags.push(reason);if(this.current.my.length||this.current.opponent.length)this.battles.push(this.current);this.current=null;this.pending={};this.resultPending=null;}
 observe(t,side,hit,confidence,raw){if(!hit||confidence<45)return;if(this.current&&t-this.lastSeen>22)this.close(this.lastSeen,'Gap boundary: check for merged or split battles');this.lastSeen=t;const key=hit.key,p=this.pending[side];this.pending[side]=p&&p.key===key&&t-p.t<5?{key,t,n:p.n+1}:{key,t,n:1};if(this.pending[side].n<2)return;if(!this.current)this.start(t);let list=this.current[side],existing=list.find(x=>x.key===key);if(existing){existing.last=t;return;}if(list.length>=3){this.close(t,'Fourth species: probable new battle, review boundary');this.start(t);list=this.current[side];}const member={...hit,first:t,last:t,confidence,raw};list.push(member);this.current.events.push({t,kind:'reveal',side,label:raw,confidence});this.current.end=t;}
 result(t,text,confidence){const value=outcome(text);if(!value||confidence<55||t-this.lastOutcome<8)return;const p=this.resultPending;this.resultPending={value,t};if(!p||p.value!==value||t-p.t>5)return;if(this.current){this.current.result=value;this.current.events.push({t,kind:'result',label:value,confidence});this.close(t);}this.lastOutcome=t;}
 move(t,text,confidence,moves){if(!this.current||confidence<55)return;const found=/^(.+?)\s+used\s+(.+?)[!.]*$/i.exec(text.trim());if(!found)return;const move=moves.find(m=>normalize(m.name)===normalize(found[2]));if(!move)return;const actor=normalize(found[1]);const sides=['my','opponent'].filter(side=>this.current[side].some(p=>p.key===actor));const side=sides.length===1?sides[0]:'unknown';const last=this.current.events.at(-1);if(last?.kind==='move'&&last.move===move.moveId&&last.actor===actor&&t-last.t<8)return;this.current.events.push({t,kind:'move',side,actor,move:move.moveId,label:text.trim(),confidence});}
 finish(t){this.close(t,'No confirmed result: partial recording or missed outcome');return this.battles;}
}
function eligible(b){return b.included!==false&&b.reviewed&&b.leadConfirmed&&b.opponent.length===3&&b.opponent.every(p=>p.id)&&new Set(b.opponent.map(p=>p.dex||p.id)).size===3;}
function aggregate(battles){const accepted=battles.filter(b=>b.reviewed&&b.included!==false),counts=new Map(),leads=new Map(),teams=new Map();for(const b of accepted){for(const p of new Map(b.opponent.map(p=>[p.id,p])).values()){if(p.id)counts.set(p.id,(counts.get(p.id)||0)+1);}if(b.leadConfirmed&&b.opponent[0]?.id)leads.set(b.opponent[0].id,(leads.get(b.opponent[0].id)||0)+1);if(eligible(b)){const ids=b.opponent.map(p=>p.id),key=[ids[0],...ids.slice(1).sort()].join('|');if(!teams.has(key))teams.set(key,{members:[ids[0],...ids.slice(1).sort()],count:0});teams.get(key).count++;}}return {accepted:accepted.length,complete:battles.filter(eligible).length,counts,leads,teams:[...teams.values()].sort((a,b)=>b.count-a.count)};}
const api={normalize,dictionary,match,outcome,Tracker,eligible,aggregate};if(typeof module!=='undefined')module.exports=api;root.MetaExtractorCore=api;
})(typeof window==='undefined'?globalThis:window);
