(function(){
'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const pct=x=>(100*x).toFixed(1)+'%',number=x=>x.toLocaleString('en-US'),move=x=>x.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const colors={steel:'#9aafb9',grass:'#86be63',flying:'#a5a5e8',water:'#75b3ef',ground:'#d1b376',dark:'#a49890',fire:'#ed9567',bug:'#bec867',normal:'#b8b5ac',dragon:'#a192ed',electric:'#dfcb69'};
let pending;
function card(title,subtitle){const c=el('section',null,'nn-card');c.append(el('h3',title),el('p',subtitle,'nn-caption'));return c;}
function chart(title,subtitle,history,series,format,range){
 const c=card(title,subtitle),wrap=el('div',null,'nn-chart'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 660 240');svg.setAttribute('role','img');svg.setAttribute('aria-label',title+'. '+subtitle);
 const create=(tag,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text!=null)n.textContent=text;svg.append(n);return n;};
 const xmin=0,xmax=Math.max(...history.map(x=>x.elapsedSeconds))/3600,values=series.flatMap(s=>history.map((h,i)=>s.get(h,i))),ymin=range?range[0]:0,ymax=range?range[1]:Math.max(...values)*1.1;
 const x=h=>55+h.elapsedSeconds/3600/xmax*585,y=v=>195-(v-ymin)/(ymax-ymin)*175;
 for(let i=0;i<=4;i++){let v=ymin+(ymax-ymin)*i/4;create('line',{x1:55,x2:640,y1:y(v),y2:y(v),class:'nn-gridline'});create('text',{x:48,y:y(v)+4,'text-anchor':'end',class:'nn-axis'},format(v));create('text',{x:55+i*585/4,y:219,'text-anchor':'middle',class:'nn-axis'},(xmax*i/4).toFixed(1)+'h');}
 series.forEach(s=>create('path',{d:history.map((h,i)=>(i?'L':'M')+x(h).toFixed(2)+','+y(s.get(h,i)).toFixed(2)).join(' '),fill:'none',stroke:s.color,'stroke-width':2.4}));
 const marker=create('line',{x1:55,x2:55,y1:20,y2:195,stroke:'currentColor','stroke-dasharray':'3 3',visibility:'hidden'});wrap.append(svg);c.append(wrap);
 const legend=el('div',null,'nn-legend');series.forEach(s=>{const l=el('span',s.name);l.style.setProperty('--series',s.color);legend.append(l);});c.append(legend);
 const control=el('input');control.type='range';control.min=0;control.max=history.length-1;control.value=history.length-1;control.setAttribute('aria-label',title+' — select round');const readout=el('output',null,'nn-readout');
 function show(i){const h=history[i];readout.textContent='Round '+h.round+' · '+(h.elapsedSeconds/3600).toFixed(2)+'h · '+series.map(s=>s.name+': '+format(s.get(h,i))).join(' · ');marker.setAttribute('x1',x(h));marker.setAttribute('x2',x(h));marker.setAttribute('visibility','visible');control.value=i;}
 control.addEventListener('input',()=>show(+control.value));svg.addEventListener('pointermove',event=>{const box=svg.getBoundingClientRect(),fraction=Math.max(0,Math.min(1,(event.clientX-box.left)/box.width));const target=(fraction*660-55)/585*xmax*3600;let i=0;history.forEach((h,j)=>{if(Math.abs(h.elapsedSeconds-target)<Math.abs(history[i].elapsedSeconds-target))i=j;});show(i);});c.append(control,readout);show(history.length-1);return c;
}
function render(d){
 const host=$('nnReport');host.replaceChildren();
 const date=x=>new Date(x).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
 host.append(el('p','Completed · '+date(d.startedAt)+'–'+date(d.endedAt)+' ET · 12 CPU workers · Top 300 by weight · Up to 5 movesets each','nn-caption'));
 const summary=el('div',null,'nn-summary');summary.append(el('h3','Melmetal / Jumpluff / Shadow Quagsire'),el('p','The pilot’s leading team held its position. Fresh testing scored '+pct(d.teams[0].validation.score)+', '+(100*d.baselines.find(b=>b.kind==='greedy-scout-coverage').delta).toFixed(1)+' percentage points above the tested coverage baseline. The search found competitive alternatives; it did not establish a globally optimal team.'));host.append(summary);
 const metrics=el('div',null,'nn-metrics');for(const [value,label] of [[pct(d.teams[0].validation.score),'Primary team · fresh test'],[number(d.runtime.newBattles),'New 3-v-3 battles'],[number(d.totalTeams),'Teams with training labels'],[d.runtime.averageCoresUsed.toFixed(1)+' / 12','Average CPU cores busy']]){const m=el('div');m.append(el('strong',value),el('span',label));metrics.append(m);}host.append(metrics);
 const grid=el('div',null,'nn-charts'),h=d.history;
 const rolling=(source,i)=>{const rows=h.slice(Math.max(0,i-4),i+1);return rows.reduce((sum,r)=>sum+r.proposalScores.find(s=>s.source===source).meanScore,0)/rows.length;};
 grid.append(chart('Search quality over time','Proposals: five-round trailing means. Leader: raw training score. Different opponents each round.',h,[{name:'Neural picks',color:'#278d87',get:(_,i)=>rolling('neural',i)},{name:'Random picks',color:'#9363c0',get:(_,i)=>rolling('random',i)},{name:'Training leader',color:'#ba8a27',get:r=>r.bestTraining}],pct,[0.2,0.8]));
 grid.append(chart('Prediction error on held-out teams','Team-mean squared error (MSE) · lower is better. Held-out identities are excluded from fitting.',h,[{name:'Neural model',color:'#278d87',get:r=>r.diagnostics.neuralMSE},{name:'Constant baseline',color:'#9363c0',get:r=>r.diagnostics.constantMSE}],v=>v.toFixed(3)));
 grid.append(chart('Simulation progress','New training battles since resume. Final screening and tests add another '+number(d.totalBattles-h.at(-1).battles)+' battles after this curve.',h,[{name:'New training battles',color:'#278d87',get:r=>r.battles-(d.totalBattles-d.runtime.newBattles)}],v=>Math.round(v/1000)+'k'));
 const comparison=card('Fresh test vs. baseline teams','Same 512 opponent fixtures, both sides. Each baseline is the average of four teams.');
 const labels={'uniform-random':'Random teams','weight-sampled-best-moves':'Weight-sampled teams','greedy-scout-coverage':'Coverage teams'};
 for(const b of [{kind:'primary',score:d.teams[0].validation.score},...d.baselines]){const row=el('div',null,'nn-bar-row');row.append(el('span',b.kind==='primary'?'Primary team':labels[b.kind]));const track=el('div',null,'nn-bar-track'),bar=el('div',null,'nn-bar');bar.style.width=100*b.score+'%';track.append(bar);row.append(track,el('strong',pct(b.score)));comparison.append(row);if(b.interval95)comparison.append(el('p','Primary advantage: +'+(100*b.delta).toFixed(1)+' pp · paired 95% interval '+b.interval95.map(x=>(100*x).toFixed(1)).join('–')+' pp','nn-caption'));}grid.append(comparison);host.append(grid);
 const heading=el('div',null,'nn-heading');heading.append(el('h3','Winning teams · fresh final test'),el('span','1,024 battles per team','nn-caption'));host.append(heading,el('p','Ordered by screening selection, before the test. Teams are listed lead first. Match score = (wins + ½ draws) / battles. Small differences between finalists may be noise.','nn-caption'));
 const teams=el('div',null,'nn-teams');d.teams.forEach((t,i)=>{const c=el('article',null,'nn-card nn-team');if(!i)c.classList.add('nn-primary');const heading=el('div',null,'nn-heading');heading.append(el('h4',i===0?'Primary · screening winner':'Screening finalist '+(i+1)),el('strong',pct(t.validation.score),'nn-test-score'));c.append(heading);
 t.team.forEach((p,j)=>{const member=el('div',null,'nn-member'),name=el('strong',(j===0?'Lead · ':'')+p.speciesName);member.append(name);const types=el('span',null,'nn-types');p.types.filter(x=>x!=='none').forEach(x=>{const badge=el('span',x);badge.style.setProperty('--type',colors[x]||'#a9b4c8');types.append(badge);});member.append(types,el('div',p.moveset.map(move).join(' · '),'nn-moves'),el('small','IVs '+Object.values(p.ivs).join('/')+' · L'+p.level+' · '+p.cp+' CP'));c.append(member);});const v=t.validation;c.append(el('p',number(v.wins)+' wins · '+number(v.draws)+' draws · '+number(v.losses)+' losses','nn-caption'),el('p','Screening '+pct(t.screen.score)+' · Training '+pct(t.trainingScore)+' · Neural forecast '+pct(t.neural.mean),'nn-caption'));teams.append(c);});host.append(teams);
 host.append(el('p','Run duration '+(d.runtime.elapsedSeconds/3600).toFixed(2)+' hours · '+number(d.totalBattles)+' cumulative battles including pilot evidence · '+number(d.fixtures)+' paired training fixtures · '+h.length+' new rounds. Final held-out MSE '+d.latestDiagnostics.neuralMSE.toFixed(4)+' vs '+d.latestDiagnostics.constantMSE.toFixed(4)+' constant baseline.','nn-caption'));
 const download=el('a','Download report data ↗');download.href='includes/pro/data/team-search.json';download.download='team-search.json';host.append(download);
}
async function load(){if(pending)return pending;pending=fetch('includes/pro/data/team-search.json').then(r=>{if(!r.ok)throw Error('Report could not be loaded');return r.json();}).then(render).catch(e=>{$('nnReport').textContent=e.message+'. Reload to retry.';pending=null;});return pending;}
document.addEventListener('neural-open',load);$('nnInfo').addEventListener('click',()=>$('nnHelp').showModal());$('nnClose').addEventListener('click',()=>$('nnHelp').close());
})();
