(function(){
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;},pct=v=>v==null?'—':(v*100).toFixed(1)+'%',C=TeamComparisonCore;
const moveName=id=>id.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function alternate(p){return p.moveset[0]!==p.recommended[0]||p.moveset.slice(1).filter(m=>m!=='none').sort().join('|')!==p.recommended.slice(1).filter(m=>m!=='none').sort().join('|');}
function identity(p,lead=false){const title=el('span',null,'nt-identity');title.append(el('strong',(lead?'Lead · ':'')+p.speciesName),el('span','PvPoke #'+(p.publishedRank??'—'),'nt-published-rank'));if(alternate(p)){const badge=el('span','Alternate Moveset','nt-alternate');badge.title='Recommended: '+p.recommended.map(moveName).join(' · ');title.append(badge);}return title;}
let dataPromise,searchPromise;
function prepareSearch(){return searchPromise||=Promise.all(['gamemaster.json','league-1500.json','meta-1500.json'].map(file=>fetch('includes/pro/data/'+file).then(r=>{if(!r.ok)throw Error('Team search data unavailable');return r.json();}))).then(([data,league,meta])=>new Promise((resolve,reject)=>{
 const worker=new Worker('includes/pro/worker.js'),timer=setTimeout(()=>{worker.terminate();reject(Error('Team search preparation timed out. Reload to retry.'));},30000);
 const finish=()=>{clearTimeout(timer);worker.terminate();};
 worker.onmessage=({data:result})=>{finish();if(result.type==='error'){reject(Error(result.error));return;}resolve({data,index:new Map(result.records.map(record=>[record.id,record])),notes:new Map(league.overall.map(row=>[row.speciesId,row.editorNotes]))});};
 worker.onerror=()=>{finish();reject(Error('Unable to prepare team search. Reload to retry.'));};
 worker.postMessage({mode:'searchIndex',data,cp:1500,published:league.overall,meta});
}));}
window.TeamBrowser={mount,async addIdentityBadges(host,p){try{const d=await(dataPromise||=fetch('includes/pro/data/team-teams/index.json').then(r=>r.json()));const pub=d.opponents.find(x=>x.speciesId===p.speciesId);if(!pub)return;host.append(el('span','PvPoke #'+pub.publishedRank,'nt-published-rank'));if(alternate({...p,recommended:pub.recommended}))host.append(el('span','Alternate Moveset','nt-alternate'));}catch(e){}}};
async function mount(host){host.textContent='Loading saved teams…';try{const d=await(dataPromise||=fetch('includes/pro/data/team-teams/index.json').then(r=>{if(!r.ok)throw Error('Saved teams unavailable');return r.json();}));host.textContent='Preparing PvPoke team search…';build(host,d,await prepareSearch());}catch(e){host.textContent=e.message;}}
function build(host,d,searchData){
 const {data:metadata,index:searchIndex,notes}=searchData,lookup=new Map(metadata.pokemon.map(p=>[p.speciesId,p]));
 const enrich=p=>({...p,types:p.types||lookup.get(p.speciesId)?.types||[],editorNotes:notes.get(p.speciesId)});
 const teams=new Map(d.rows.map(r=>[r.id,r.team.map(i=>enrich(d.variants[i]))]));
 const savedRank=new Map([...d.rows].sort((a,b)=>b.selection-a.selection||a.id-b.id).map((r,i)=>[C.signature(teams.get(r.id)),i+1]));
 const rowByTeam=new Map(d.rows.map(r=>[C.signature(teams.get(r.id)),r]));
 const metrics=new Map(d.rows.map(r=>[r.id,C.ranks(teams.get(r.id))]));
 const member=(p,lead=false)=>{const n=el('div',null,'nt-row-member');n.append(identity(p,lead),PvPProDetail.pokemonTypes(p),PvPProDetail.moves(p.moveset,metadata));return n;};
 const chunks=new Map();async function loadMatches(row){if(!row)return {test:[],screen:[],baseline:[],training:[]};if(!chunks.has(row.chunk))chunks.set(row.chunk,fetch('includes/pro/data/team-teams/'+row.chunk+'.json').then(r=>{if(!r.ok)throw Error('Matchup data unavailable');return r.json();}));return (await chunks.get(row.chunk))[row.id];}
 host.replaceChildren();let page=0,key='selection',direction=-1,selected=null,activeWorker=null,request=0;const picked=new Set();
 const note=el('p',d.counts.teams.toLocaleString()+' saved teams · '+d.counts.screened+' screened · '+d.counts.tested+' final-tested · '+d.counts.baselines+' baseline comparisons. Training samples vary; compare shared fixtures to assess a team change. Alphabetical bench display preserves the simulation’s original order.','nn-caption');
 const toolbar=el('div',null,'nt-toolbar'),search=el('input'),population=el('select'),compare=el('button','Compare Teams (0 / 2)','secondary');compare.type='button';compare.disabled=true;search.type='search';search.placeholder='melmetal&cramorant · lead:melmetal · lead:@counter';search.setAttribute('aria-label','Search saved teams');for(const [v,l] of [['all','All saved teams'],['screen','Screened teams (24)'],['test','Final-test finalists (8)'],['baseline','Baseline comparisons (12)']]){const o=el('option',l);o.value=v;population.append(o);}population.setAttribute('aria-label','Team evidence filter');toolbar.append(search,population,compare);
 const layout=el('div',null,'nt-layout'),left=el('section'),scroll=el('div',null,'table-scroll'),table=el('table',null,'nt-table'),head=el('thead'),body=el('tbody'),pager=el('div',null,'nt-toolbar'),prev=el('button','Previous','secondary'),next=el('button','Next','secondary'),count=el('span',null,'nn-caption'),detail=el('aside',null,'nt-detail');detail.hidden=true;table.append(el('caption','Saved team rankings'),head,body);scroll.append(table);pager.append(prev,count,next);left.append(scroll,pager);layout.append(left,detail);host.append(note,toolbar,el('p','& = AND across members · , = OR · ! excludes matches · @ searches used moves · lead: restricts a term to the lead. Select two checkboxes to compare.','nn-caption'),layout);
 const comparison=TeamComparison.create({host,data:d,metadata,searchIndex,teams,loadMatches,rowByTeam,member,battleGraph:(host,r,swapped)=>battleGraph(host,r,swapped,metadata),savedRank});
 compare.addEventListener('click',()=>{const ids=[...picked];comparison.open({row:d.rows.find(r=>r.id===ids[0]),team:teams.get(ids[0])},{row:d.rows.find(r=>r.id===ids[1]),team:teams.get(ids[1])});});
 const columns=[['selection','Selection'],['training','Training'],['games','Battles'],['screen','Screening'],['test','Fresh test'],['minRank','Min Ranking'],['maxRank','Max Ranking'],['avgRank','Average Ranking']];
 function render(){const matches=PvPProSearch.compileTeam(search.value,metadata);let rows=d.rows.filter(r=>(population.value==='all'||(population.value==='test'?r.finalist:r[population.value]!=null))&&matches(teams.get(r.id),searchIndex));const value=(r,k)=>metrics.get(r.id)[k]??r[k];rows.sort((a,b)=>{if(value(a,key)==null)return value(b,key)==null?a.id-b.id:1;if(value(b,key)==null)return -1;return direction*(value(a,key)-value(b,key))||a.id-b.id;});page=Math.min(page,Math.max(0,Math.ceil(rows.length/500)-1));head.replaceChildren();const tr=el('tr');tr.append(el('th','Compare'),el('th','Rank'),el('th','Lead'),el('th','Backline · alphabetical'));for(const [k,title] of columns){const th=el('th'),btn=el('button',title+(key===k?(direction<0?' ↓':' ↑'):''),'secondary');btn.type='button';btn.addEventListener('click',()=>{direction=key===k?-direction:k.endsWith('Rank')?1:-1;key=k;page=0;render();});th.append(btn);if(k.endsWith('Rank'))th.title='Published Great League Pokémon ranks; lower is better.';th.setAttribute('aria-sort',key===k?(direction<0?'descending':'ascending'):'none');tr.append(th);}head.append(tr);body.replaceChildren();
 for(const [j,r] of rows.slice(page*500,(page+1)*500).entries()){const tr=el('tr');if(r.id===selected)tr.className='nt-selected';const pickCell=el('td'),pick=el('input');pick.type='checkbox';pick.checked=picked.has(r.id);pick.disabled=picked.size===2&&!pick.checked;pick.setAttribute('aria-label','Compare team '+r.id);pick.addEventListener('change',()=>{pick.checked?picked.add(r.id):picked.delete(r.id);compare.textContent='Compare Teams ('+picked.size+' / 2)';compare.disabled=picked.size!==2;render();});pickCell.append(pick);tr.append(pickCell,el('td',String(page*500+j+1)));
 const ordered=C.bench(teams.get(r.id));for(const [label,entries] of [['lead',[ordered[0]]],['team',ordered.slice(1)]]){const td=el('td'),btn=el('button',null,'nt-team-button');btn.type='button';btn.setAttribute('aria-label',(label==='lead'?'View lead for team ':'View team ')+r.id+' · '+ordered.map(p=>p.speciesName).join(', '));btn.setAttribute('aria-expanded',String(selected===r.id));entries.forEach(p=>btn.append(member(p)));btn.addEventListener('click',()=>open(r));td.append(btn);tr.append(td);}for(const [k] of columns){const v=value(r,k),td=el('td',k==='games'?r.games.toLocaleString():k.endsWith('Rank')?(v==null?'—':k==='avgRank'?v.toFixed(1):String(v)):pct(v));if(k===key)td.className='nt-active-score';tr.append(td);}body.append(tr);}
 if(!rows.length){const tr=el('tr'),td=el('td','No saved teams match this search.');td.colSpan=4+columns.length;tr.append(td);body.append(tr);}prev.disabled=page===0;next.disabled=(page+1)*500>=rows.length;count.textContent=rows.length.toLocaleString()+' teams · Page '+(page+1)+' / '+Math.max(1,Math.ceil(rows.length/500))+' · 500 per page';}
 search.addEventListener('input',()=>{page=0;render();});population.addEventListener('change',()=>{page=0;render();});prev.addEventListener('click',()=>{page--;render();});next.addEventListener('click',()=>{page++;render();});
 async function open(row){selected=row.id;const token=++request;activeWorker?.terminate();render();detail.hidden=false;layout.classList.add('nt-open');detail.replaceChildren();if(matchMedia('(max-width:1050px)').matches)detail.scrollIntoView({behavior:'smooth',block:'start'});const title=el('div',null,'nn-heading'),close=el('button','Close','secondary');close.addEventListener('click',()=>{++request;activeWorker?.terminate();selected=null;detail.hidden=true;layout.classList.remove('nt-open');render();});title.append(el('h3','Team details'),close);detail.append(title);
 C.bench(teams.get(row.id)).forEach((p,k)=>{const m=member(p,k===0);m.classList.add('nn-member');m.append(el('small','IVs '+Object.values(p.ivs).join('/')+' · L'+p.level+' · '+p.cp+' CP'));detail.append(m);});const status=el('p','Loading battles…','nn-caption');detail.append(status);
 try{const all=await loadMatches(row);if(token!==request)return;status.remove();const stage=el('select');stage.setAttribute('aria-label','Matchup evidence for selected team');for(const [k,t] of [['test','Fresh final test'],['screen','Fresh screening'],['baseline','Baseline comparison'],['training','Training']])if(all[k].length){const o=el('option',t+' · '+all[k].length+' paired fixtures');o.value=k;stage.append(o);}detail.append(stage,el('p','Each result covers two battles with sides swapped. Split / draws can contain one win and one loss, or draws. Saved opponent team ranks use Selection; unranked teams sort by average Pokémon rank.','nn-caption'));const matchHost=el('div'),battleHost=el('section',null,'nt-battle');detail.append(matchHost,battleHost);
 function matches(){activeWorker?.terminate();battleHost.replaceChildren();matchHost.replaceChildren(el('h4','Battles'));const input=el('input'),reverse=el('button','Best ranked first ↓','secondary'),tools=el('div',null,'nt-toolbar');input.type='search';input.placeholder='Search opponent teams · lead: · @';input.setAttribute('aria-label','Search opponent teams');tools.append(input,reverse);matchHost.append(tools);const list=el('div'),more=el('button','Show more','secondary');matchHost.append(list,more);let limit=25,sign=1;const cases=all[stage.value].map((m,i)=>{const opponent=m[0].map(i=>enrich(d.opponents[i]));return {opponent,seed:m[1],score:m[2],index:i,rank:savedRank.get(C.signature(opponent)),avg:C.ranks(opponent).avgRank};});
 function fill(){const match=PvPProSearch.compileTeam(input.value,metadata),ranked=cases.filter(c=>match(c.opponent,searchIndex)).sort((a,b)=>sign*((a.rank??Infinity)-(b.rank??Infinity))||sign*(a.avg-b.avg)||a.index-b.index);list.replaceChildren();for(const c of ranked.slice(0,limit)){const btn=el('button',null,'nt-match');btn.type='button';btn.append(el('span','Lead: '+c.opponent[0].speciesName+' · '+C.bench(c.opponent).slice(1).map(p=>p.speciesName).join(' / ')+' · '+(c.rank?'Team #'+c.rank:'Unranked · avg Pokémon #'+c.avg.toFixed(1))),el('strong',C.outcome(c.score),'nt-result-'+(c.score>.5?'win':c.score<.5?'loss':'split')));btn.addEventListener('click',()=>replay(c));list.append(btn);}if(!ranked.length)list.append(el('p','No battles match this search.','nn-caption'));more.hidden=limit>=ranked.length;}
 input.addEventListener('input',()=>{limit=25;fill();});reverse.addEventListener('click',()=>{sign=-sign;reverse.textContent=sign===1?'Best ranked first ↓':'Worst ranked first ↑';fill();});more.addEventListener('click',()=>{limit+=50;fill();});fill();}
 function replay(c){activeWorker?.terminate();const worker=new Worker('includes/pro/team-replay-worker.js?v=team-comparison-1');activeWorker=worker;const replayToken=++request;battleHost.replaceChildren(el('h3','Simulated team battle'),el('p','Replaying both sides…','nn-caption'));const focus=()=>detail.scrollTo({top:detail.scrollTop+battleHost.getBoundingClientRect().top-detail.getBoundingClientRect().top-12,behavior:'smooth'});focus();const timer=setTimeout(()=>{worker.terminate();if(request===replayToken)battleHost.append(el('p','Replay timed out.'));},30000);
 worker.onmessage=({data:r})=>{clearTimeout(timer);worker.terminate();if(request!==replayToken)return;if(r.error){battleHost.replaceChildren(el('p',r.error));return;}battleHost.replaceChildren(el('h3','Simulated team battle'),el('p',Math.abs(r.pairedScore-c.score)<1e-10?'Verified: matches stored score '+pct(c.score):'Replay differs from saved result; treat it as a reconstruction.','nn-caption'));const toggle=el('select'),graph=el('div'),button=el('button','Compare Teams','secondary');toggle.setAttribute('aria-label','Replay side');for(const [v,t] of [['a','Original sides'],['b','Swapped sides']]){const o=el('option',t);o.value=v;toggle.append(o);}button.addEventListener('click',()=>comparison.open({row,team:teams.get(row.id)},{row:rowByTeam.get(C.signature(c.opponent)),team:c.opponent}));battleHost.append(toggle,graph,button);const draw=()=>battleGraph(graph,r[toggle.value],toggle.value==='b');toggle.addEventListener('change',draw);draw();focus();};worker.onerror=()=>{clearTimeout(timer);worker.terminate();if(request===replayToken)battleHost.append(el('p','Replay failed.'));};worker.postMessage({teams:[teams.get(row.id),c.opponent],seed:c.seed});}
 stage.addEventListener('change',()=>{++request;matches();});matches();
 }catch(e){if(token===request)status.textContent=e.message;}}
 render();
}
function battleGraph(host,result,swapped){host.replaceChildren();const score=swapped?1-result.score:result.score;host.append(el('p','Your team: '+(score===1?'Win':score===0?'Loss':'Draw')+' · '+result.turns+' turns','nn-caption'));const stats=(swapped?result.teamStats.slice().reverse():result.teamStats).flat(),colors=['#1e8e89','#44b6aa','#83c9ac','#cb624d','#d79943','#b87198'];const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 650 280');svg.setAttribute('role','img');svg.setAttribute('aria-label','Remaining HP of all six Pokémon over simulated time');const add=(tag,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!=null)n.textContent=text;svg.append(n);};const xmax=Math.max(1,result.samples.at(-1)[0]),x=t=>45+575*t/xmax,y=p=>230-p*200;
 for(let i=0;i<=4;i++){add('line',{x1:45,x2:620,y1:y(i/4),y2:y(i/4),class:'nn-gridline'});add('text',{x:40,y:y(i/4)+4,'text-anchor':'end',class:'nn-axis'},i*25+'%');add('text',{x:45+575*i/4,y:250,'text-anchor':'middle',class:'nn-axis'},Math.round(xmax*i/4)+'s');}
 stats.forEach((p,i)=>{const j=swapped?(i+3)%6:i;let previous=null;const path=[];result.samples.forEach(s=>{const px=x(s[0]),py=y(s[2][j]/p.maxHP);path.push(previous==null?'M'+px+','+py:'H'+px+'V'+py);previous=px;});add('path',{d:path.join(' '),stroke:colors[i],fill:'none','stroke-width':2,'stroke-dasharray':i>=3?'5 3':'none'});});host.append(svg);const legend=el('div',null,'nn-legend');stats.forEach((p,i)=>{const n=el('span',(i<3?'Your ':'Opponent ')+p.name);n.style.setProperty('--series',colors[i]);legend.append(n);});host.append(legend,el('p','HP as a percentage of each Pokémon’s starting HP. Virtual elapsed seconds include countdowns and charged-move animations. Solid lines: your team; dashed: opponents.','nn-caption'));const events=el('details'),summary=el('summary','Battle events · charged moves, shields, switches and faints');events.append(summary);const list=el('ol',null,'nt-events');result.timeline.filter(e=>!e.type.startsWith('fast ')).forEach(e=>list.append(el('li','Turn '+e.turn+' · '+((swapped?1-e.actor:e.actor)===0?'Your team':'Opponent')+' · '+e.name+' ('+e.type+')')));events.append(list);host.append(events);}

})();
