(function(){
'use strict';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;},pct=v=>v==null?'—':(v*100).toFixed(1)+'%',moves=p=>p.moveset.map(m=>m.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())).join(' · ');
function alternate(p){return p.moveset[0]!==p.recommended[0]||p.moveset.slice(1).filter(m=>m!=='none').sort().join('|')!==p.recommended.slice(1).filter(m=>m!=='none').sort().join('|');}
function identity(p,lead=false){const title=el('span',null,'nt-identity');title.append(el('strong',(lead?'Lead · ':'')+p.speciesName),el('span','PvPoke #'+(p.publishedRank??'—'),'nt-published-rank'));if(alternate(p)){const badge=el('span','Alternate Moveset','nt-alternate');badge.title='Recommended: '+p.recommended.map(m=>m.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())).join(' · ');title.append(badge);}return title;}
let dataPromise,searchPromise;
function prepareSearch(){return searchPromise||=Promise.all(['gamemaster.json','league-1500.json','meta-1500.json'].map(file=>fetch('includes/pro/data/'+file).then(r=>{if(!r.ok)throw Error('Team search data unavailable');return r.json();}))).then(([data,league,meta])=>new Promise((resolve,reject)=>{
 const worker=new Worker('includes/pro/worker.js'),timer=setTimeout(()=>{worker.terminate();reject(Error('Team search preparation timed out. Reload to retry.'));},30000);
 const finish=()=>{clearTimeout(timer);worker.terminate();};
 worker.onmessage=({data:result})=>{finish();if(result.type==='error'){reject(Error(result.error));return;}resolve({data,index:new Map(result.records.map(record=>[record.id,record])),notes:new Map(league.overall.map(row=>[row.speciesId,row.editorNotes]))});};
 worker.onerror=()=>{finish();reject(Error('Unable to prepare team search. Reload to retry.'));};
 worker.postMessage({mode:'searchIndex',data,cp:1500,published:league.overall,meta});
}));}
window.TeamBrowser={mount,async addIdentityBadges(host,p){try{const d=await(dataPromise||=fetch('includes/pro/data/team-teams/index.json').then(r=>r.json()));const pub=d.opponents.find(x=>x.speciesId===p.speciesId);if(!pub)return;const info={...p,publishedRank:pub.publishedRank,recommended:pub.recommended};host.append(el('span','PvPoke #'+pub.publishedRank,'nt-published-rank'));if(alternate(info))host.append(el('span','Alternate Moveset','nt-alternate'));}catch(e){}}};
async function mount(host){host.textContent='Loading saved teams…';try{const d=await(dataPromise||=fetch('includes/pro/data/team-teams/index.json').then(r=>{if(!r.ok)throw Error('Saved teams unavailable');return r.json();}));host.textContent='Preparing PvPoke team search…';const searchData=await prepareSearch();build(host,d,searchData);}catch(e){host.textContent=e.message;}}
function build(host,d,searchData){
 const {data:searchMetadata,index:searchIndex,notes}=searchData;const searchableTeams=new Map(d.rows.map(r=>[r.id,r.team.map(i=>({...d.variants[i],editorNotes:notes.get(d.variants[i].speciesId)}))]));
 host.replaceChildren();let page=0,key='selection',direction=-1,selected=null,activeWorker=null,request=0;const chunks=new Map();
 const note=el('p',d.counts.teams.toLocaleString()+' saved teams · '+d.counts.screened+' screened · '+d.counts.tested+' final-tested · '+d.counts.baselines+' baseline comparisons. Default order uses cautious training selection score. Training opponents and sample sizes vary; only fresh-test finalists share the same untouched opponent panel.','nn-caption');
 const toolbar=el('div',null,'nt-toolbar'),search=el('input'),population=el('select');search.type='search';search.placeholder='Search teams: melmetal&cramorant&@counter';search.setAttribute('aria-label','Search saved teams');for(const [v,l] of [['all','All saved teams'],['screen','Screened teams (24)'],['test','Final-test finalists (8)'],['baseline','Baseline comparisons (12)']]){const o=el('option',l);o.value=v;population.append(o);}population.setAttribute('aria-label','Team evidence filter');toolbar.append(search,population);
 const layout=el('div',null,'nt-layout'),left=el('section'),scroll=el('div',null,'table-scroll'),table=el('table',null,'nt-table'),caption=el('caption','Saved team rankings'),head=el('thead'),body=el('tbody'),pager=el('div',null,'nt-toolbar'),prev=el('button','Previous','secondary'),next=el('button','Next','secondary'),count=el('span',null,'nn-caption'),detail=el('aside',null,'nt-detail');detail.hidden=true;table.append(caption,head,body);scroll.append(table);pager.append(prev,count,next);left.append(scroll,pager);layout.append(left,detail);const searchHelp=el('p','PvPoke search syntax · & = AND across team members · , = OR · ! excludes teams containing a match · @ searches the moves actually used.','nn-caption');host.append(note,toolbar,searchHelp,layout);
 const columns=[['selection','Selection score'],['training','Training score'],['games','Training battles'],['screen','Screening score'],['test','Fresh test score']];
 function render(){const matchesTeam=PvPProSearch.compileTeam(search.value,searchMetadata);let rows=d.rows.filter(r=>(population.value==='all'||(population.value==='test'?r.finalist:r[population.value]!=null))&&matchesTeam(searchableTeams.get(r.id),searchIndex));rows.sort((a,b)=>{if(a[key]==null)return b[key]==null?a.id-b.id:1;if(b[key]==null)return -1;return direction*(a[key]-b[key])||a.id-b.id;});page=Math.min(page,Math.max(0,Math.ceil(rows.length/500)-1));head.replaceChildren();const tr=el('tr');tr.append(el('th','Rank'),el('th','Team · lead first'));for(const [k,title] of columns){const th=el('th'),btn=el('button',title+(key===k?(direction<0?' ↓':' ↑'):''),'secondary');btn.title=title;btn.textContent=({selection:'Selection',training:'Training',games:'Battles',screen:'Screening',test:'Fresh test'}[k])+(key===k?(direction<0?' ↓':' ↑'):'');btn.type='button';btn.addEventListener('click',()=>{direction=key===k?-direction:-1;key=k;page=0;render();});th.append(btn);th.setAttribute('aria-sort',key===k?(direction<0?'descending':'ascending'):'none');tr.append(th);}head.append(tr);body.replaceChildren();
 rows.slice(page*500,(page+1)*500).forEach((r,j)=>{const tr=el('tr');if(r.id===selected)tr.className='nt-selected';tr.append(el('td',String(page*500+j+1)));const team=el('td'),button=el('button',null,'nt-team-button');button.type='button';button.setAttribute('aria-expanded',String(r.id===selected));button.setAttribute('aria-label','View team '+r.team.map(i=>d.variants[i].speciesName).join(', '));r.team.forEach((i,k)=>{const p=d.variants[i],member=el('span',null,'nt-row-member');member.append(identity(p,k===0),el('small',moves(p)));button.append(member);});button.addEventListener('click',()=>open(r));team.append(button);if(r.baseline)team.append(el('span','Baseline · '+r.baseline.replaceAll('-',' '),'nt-published-rank'));tr.append(team);columns.forEach(([k])=>{const td=el('td',k==='games'?r.games.toLocaleString():pct(r[k]));if(k===key)td.className='nt-active-score';tr.append(td);});body.append(tr);});if(!rows.length){const empty=el('tr'),cell=el('td','No saved teams match this search.');cell.colSpan=2+columns.length;empty.append(cell);body.append(empty);}prev.disabled=page===0;next.disabled=(page+1)*500>=rows.length;count.textContent=rows.length.toLocaleString()+' teams · Page '+(page+1)+' / '+Math.max(1,Math.ceil(rows.length/500))+' · 500 per page';}
 search.addEventListener('input',()=>{page=0;render();});population.addEventListener('change',()=>{page=0;render();});prev.addEventListener('click',()=>{page--;render();});next.addEventListener('click',()=>{page++;render();});
 async function open(row){selected=row.id;const token=++request;activeWorker?.terminate();activeWorker=null;render();detail.hidden=false;layout.classList.add('nt-open');detail.replaceChildren();if(matchMedia('(max-width:1050px)').matches)detail.scrollIntoView({behavior:'smooth',block:'start'});const title=el('div',null,'nn-heading'),close=el('button','Close','secondary');close.type='button';close.addEventListener('click',()=>{++request;activeWorker?.terminate();selected=null;detail.hidden=true;layout.classList.remove('nt-open');render();});title.append(el('h3','Team details'),close);detail.append(title);
 row.team.forEach((i,k)=>{const p=d.variants[i],m=el('div',null,'nn-member');m.append(identity(p,k===0),el('div',moves(p),'nn-moves'),el('small',p.types.filter(t=>t!=='none').join(' / ')+' · IVs '+Object.values(p.ivs).join('/')+' · L'+p.level+' · '+p.cp+' CP'));detail.append(m);});const status=el('p','Loading stored opponents…','nn-caption');detail.append(status);
 try{if(!chunks.has(row.chunk))chunks.set(row.chunk,fetch('includes/pro/data/team-teams/'+row.chunk+'.json').then(r=>{if(!r.ok)throw Error('Matchup data unavailable');return r.json();}));const all=(await chunks.get(row.chunk))[row.id];if(token!==request)return;status.remove();const stage=el('select');stage.setAttribute('aria-label','Matchup evidence for selected team');for(const [k,title] of [['test','Fresh final test'],['screen','Fresh screening'],['baseline','Baseline comparison test'],['training','Training']])if(all[k].length){const o=el('option',title+' · '+all[k].length+' paired fixtures');o.value=k;stage.append(o);}detail.append(stage,el('p','Stored scores average two battles with sides swapped. Click a fixture to reconstruct both battles from its original seed.','nn-caption'));const matchHost=el('div'),battleHost=el('section',null,'nt-battle');detail.append(matchHost,battleHost);
 function matches(){activeWorker?.terminate();battleHost.replaceChildren();const cases=all[stage.value].map((m,i)=>({opponent:m[0].map(i=>d.opponents[i]),seed:m[1],score:m[2],index:i}));matchHost.replaceChildren();const groups=el('div',null,'nt-match-groups');for(const [label,sign] of [['Best battles',-1],['Worst battles',1]]){const box=el('section');box.append(el('h4',label));let limit=10;const list=el('div'),more=el('button','Show more','secondary');more.type='button';const ranked=[...cases].sort((a,b)=>sign*(a.score-b.score)||a.index-b.index);function fill(){list.replaceChildren();for(const c of ranked.slice(0,limit)){const btn=el('button',null,'nt-match');btn.type='button';btn.append(el('span',c.opponent.map(p=>p.speciesName).join(' / ')),el('strong',pct(c.score)));btn.addEventListener('click',()=>replay(c));list.append(btn);}more.hidden=limit>=ranked.length;}more.addEventListener('click',()=>{limit+=20;fill();});fill();box.append(list,more);groups.append(box);}matchHost.append(groups);}
 function replay(c){activeWorker?.terminate();const worker=new Worker('includes/pro/team-replay-worker.js');activeWorker=worker;const replayToken=++request;battleHost.replaceChildren(el('h3','Simulated team battle'),el('p','Replaying both sides with the original seed…','nn-caption'));const focusBattle=()=>detail.scrollTo({top:detail.scrollTop+battleHost.getBoundingClientRect().top-detail.getBoundingClientRect().top-12,behavior:'smooth'});focusBattle();const timeout=setTimeout(()=>{worker.terminate();if(request===replayToken)battleHost.append(el('p','Replay exceeded the time limit. Select another fixture.'));},30000);
 worker.onmessage=({data:result})=>{clearTimeout(timeout);worker.terminate();if(request!==replayToken)return;if(result.error){battleHost.replaceChildren(el('p','Replay failed: '+result.error));return;}const valid=Math.abs(result.pairedScore-c.score)<1e-10;const heading=el('h3','Simulated team battle'),check=el('p',valid?'Verified: replay matches stored paired score '+pct(c.score):'Replay differs from the stored result: '+pct(result.pairedScore)+' vs '+pct(c.score)+'. Treat this graph as a reconstruction, not the original battle.','nn-caption');battleHost.replaceChildren(heading,check);const toggle=el('select');toggle.setAttribute('aria-label','Replay side');for(const [v,l] of [['a','Original sides'],['b','Swapped sides']]){const o=el('option',l);o.value=v;toggle.append(o);}const graph=el('div');battleHost.append(toggle,graph);const draw=()=>battleGraph(graph,result[toggle.value],toggle.value==='b');toggle.addEventListener('change',draw);draw();focusBattle();};worker.onerror=()=>{clearTimeout(timeout);worker.terminate();if(request===replayToken)battleHost.append(el('p','Replay worker failed. Please reload and try again.'));};worker.postMessage({teams:[row.team.map(i=>d.variants[i]),c.opponent],seed:c.seed});}
 stage.addEventListener('change',()=>{++request;matches();});matches();
 }catch(e){if(token===request)status.textContent=e.message;}}
 render();
}
function battleGraph(host,result,swapped){host.replaceChildren();const score=swapped?1-result.score:result.score;host.append(el('p','Your team: '+(score===1?'Win':score===0?'Loss':'Draw')+' · '+result.turns+' turns','nn-caption'));const stats=(swapped?result.teamStats.slice().reverse():result.teamStats).flat(),colors=['#1e8e89','#44b6aa','#83c9ac','#cb624d','#d79943','#b87198'];const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 650 280');svg.setAttribute('role','img');svg.setAttribute('aria-label','Remaining HP of all six Pokémon over simulated time');const add=(tag,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!=null)n.textContent=text;svg.append(n);};const xmax=Math.max(1,result.samples.at(-1)[0]),x=t=>45+575*t/xmax,y=p=>230-p*200;
 for(let i=0;i<=4;i++){add('line',{x1:45,x2:620,y1:y(i/4),y2:y(i/4),class:'nn-gridline'});add('text',{x:40,y:y(i/4)+4,'text-anchor':'end',class:'nn-axis'},i*25+'%');add('text',{x:45+575*i/4,y:250,'text-anchor':'middle',class:'nn-axis'},Math.round(xmax*i/4)+'s');}
 stats.forEach((p,i)=>{const j=swapped?(i+3)%6:i;let previous=null;const path=[];result.samples.forEach(s=>{const px=x(s[0]),py=y(s[2][j]/p.maxHP);path.push(previous==null?'M'+px+','+py:'H'+px+'V'+py);previous=px;});add('path',{d:path.join(' '),stroke:colors[i],fill:'none','stroke-width':2,'stroke-dasharray':i>=3?'5 3':'none'});});host.append(svg);const legend=el('div',null,'nn-legend');stats.forEach((p,i)=>{const n=el('span',(i<3?'Your ':'Opponent ')+p.name);n.style.setProperty('--series',colors[i]);legend.append(n);});host.append(legend,el('p','HP as a percentage of each Pokémon’s starting HP. Virtual elapsed seconds include countdowns and charged-move animations. Solid lines: your team; dashed: opponents.','nn-caption'));const events=el('details'),summary=el('summary','Battle events · charged moves, shields, switches and faints');events.append(summary);const list=el('ol',null,'nt-events');result.timeline.filter(e=>!e.type.startsWith('fast ')).forEach(e=>list.append(el('li','Turn '+e.turn+' · '+((swapped?1-e.actor:e.actor)===0?'Your team':'Opponent')+' · '+e.name+' ('+e.type+')')));events.append(list);host.append(events);}
})();
