const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../includes/meta/core.js'),gm=require('../includes/pro/data/gamemaster.json');
const d=C.dictionary(gm.pokemon),hit=name=>C.match(name,d);
test('multiword names and accents normalize, CP ignored',()=>{assert.equal(hit('Mr. Mime').quality,'exact');assert.ok(hit('Flabébé'));assert.ok(hit('Melmetal CP 1499'));});
test('regional and Shadow ambiguity are never assigned automatically',()=>{assert.equal(hit('Corsola').id,'');assert.ok(hit('Corsola').candidates.some(p=>p.id==='corsola_galarian'));assert.equal(hit('Feraligatr').id,'');});
test('fuzzy OCR is only a suggestion',()=>{assert.equal(hit('Melmeta1').quality,'suggestion');assert.equal(hit('Melmeta1').id,'');assert.equal(hit('random text from menu'),null);});
test('two sightings, duplicate filtering, missing result retained',()=>{const t=new C.Tracker();t.observe(0,'opponent',hit('Melmetal'),90,'Melmetal');assert.equal(t.current,null);t.observe(.5,'opponent',hit('Melmetal'),90,'Melmetal');t.observe(1,'opponent',hit('Melmetal'),90,'Melmetal');assert.equal(t.current.opponent.length,1);assert.equal(t.finish(2)[0].result,'Unknown');});
test('short charge HUD absence does not split a battle',()=>{const t=new C.Tracker();for(const n of [0,.5,15,15.5])t.observe(n,'opponent',hit('Melmetal'),90,'Melmetal');assert.equal(t.finish(16).length,1);});
test('a long gap and fourth species create reviewable boundaries',()=>{const t=new C.Tracker();for(const [i,name] of ['Melmetal','Jumpluff','Cramorant','Clodsire'].entries()){t.observe(i*2,'opponent',hit(name),90,name);t.observe(i*2+.5,'opponent',hit(name),90,name);}assert.equal(t.finish(9).length,2);const x=new C.Tracker();[0,.5,30,30.5].forEach(n=>x.observe(n,'opponent',hit('Melmetal'),90,'Melmetal'));assert.equal(x.finish(31).length,2);});
test('results require repeated readings and never turn unknown into a loss',()=>{const t=new C.Tracker();[0,.5].forEach(n=>t.observe(n,'opponent',hit('Melmetal'),90,'Melmetal'));t.result(3,'YOU WIN!',90);assert.equal(t.battles.length,0);t.result(3.5,'YOU WIN!',90);assert.equal(t.battles[0].result,'Win');assert.equal(C.outcome('Good effort!'),'Loss');assert.equal(C.outcome('Continue'),null);});
test('meta counts reviewed observations, training requires a complete verified lead',()=>{const b={reviewed:true,leadConfirmed:true,opponent:['melmetal','cramorant','jumpluff'].map(id=>({id}))};assert.ok(C.eligible(b));assert.equal(C.aggregate([b,{...b,reviewed:false}]).accepted,1);assert.equal(C.aggregate([b,{...b,leadConfirmed:false}]).complete,1);assert.equal(C.aggregate([b,{...b,opponent:b.opponent.slice(0,2)}]).counts.get('melmetal'),2);});
test('bench permutations aggregate but different leads do not',()=>{const b={reviewed:true,leadConfirmed:true,opponent:['melmetal','cramorant','jumpluff'].map(id=>({id}))};assert.equal(C.aggregate([b,{...b,opponent:[b.opponent[0],b.opponent[2],b.opponent[1]]}]).teams[0].count,2);assert.equal(C.aggregate([b,{...b,opponent:[b.opponent[1],b.opponent[0],b.opponent[2]]}]).teams.length,2);});

test('species clause excludes two forms with the same Pokédex number',()=>{assert.equal(C.eligible({reviewed:true,leadConfirmed:true,opponent:[{id:'feraligatr',dex:160},{id:'feraligatr_shadow',dex:160},{id:'melmetal',dex:809}]}),false);});
test('result text tolerates a single glyph error but not arbitrary nearby strings',()=>{assert.equal(C.outcome('YOUMW/IN!'),'Win');assert.equal(C.outcome('Good eff0rt!'),'Loss');assert.equal(C.outcome('Next battle'),null);});

test('excluded observations are recoverable but do not count; duplicate sightings count once',()=>{const b={reviewed:true,leadConfirmed:true,opponent:[{id:'melmetal'},{id:'melmetal'}]};assert.equal(C.aggregate([b]).counts.get('melmetal'),1);assert.equal(C.aggregate([{...b,included:false}]).accepted,0);});
