#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),crypto=require('node:crypto');const {options,atomic,freshEvaluationSeeds}=require('./common.cjs');const {defaultWorkers}=require('../pool.cjs');
const opts=options(process.argv.slice(2),{until:'',hours:6,out:'training/runs/team-search-v3',pool:'',meta:'hybrid',usageFile:'',usageHalfLifeDays:0,usageAsOf:'',usagePriorStrength:500,lookaheadTurns:24,decisionInterval:4,metaWeightPower:1.25,warmStart:'',runId:'',rounds:1000000,workers:defaultWorkers(),initialTeams:128,batchTeams:24,opponents:64,validationTeams:8,validationOpponents:512,screenTeams:24,screenOpponents:512,baselineCount:12,candidates:12000,epochs:6,hidden:16,ensemble:12,referenceOpponents:256,fitFixtures:48000,validationSeed:0,seed:20261009,resume:false});
if(opts.help){console.log('node training/team-search/launch.cjs [search options] · detached caffeinate process, training.log and launch.json');process.exit(0);}
if(opts.until&&(!Number.isFinite(Date.parse(opts.until))||Date.parse(opts.until)<=Date.now()))throw Error('until must be a future ISO timestamp');
const directory=path.resolve(opts.out);fs.mkdirSync(directory,{recursive:true});const marker=path.join(directory,'launch.json');
if(fs.existsSync(marker)){const old=JSON.parse(fs.readFileSync(marker));try{process.kill(old.pid,0);throw Error('A run is already active at PID '+old.pid);}catch(e){if(e.code!=='ESRCH')throw e;}}
opts.runId=crypto.randomBytes(16).toString('hex');
if(!opts.validationSeed){if(opts.resume)opts.validationSeed=JSON.parse(fs.readFileSync(path.join(directory,'checkpoint.json'))).config.validationSeed;else{const used=opts.warmStart?JSON.parse(fs.readFileSync(path.resolve(opts.warmStart))).evaluationEvidence?.fixtureSeeds||[]:[];do{opts.validationSeed=crypto.randomBytes(4).readUInt32LE(0)||1;}while(!freshEvaluationSeeds(opts.validationSeed,used));}}
const args=[path.join(__dirname,'search.cjs')];for(const [key,value] of Object.entries(opts)){if(key==='help'||value===''||value===false)continue;const flag='--'+key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase());args.push(flag);if(value!==true)args.push(String(value));}
const log=path.join(directory,'training.log'),fd=fs.openSync(log,'a');const executable=process.platform==='darwin'?'/usr/bin/caffeinate':process.execPath;const launchArgs=process.platform==='darwin'?['-i',process.execPath,...args]:args;
const child=spawn(executable,launchArgs,{cwd:process.cwd(),detached:true,stdio:['ignore',fd,fd]});child.on('error',e=>{console.error(e);process.exitCode=1;});child.once('spawn',()=>{atomic(marker,{pid:child.pid,runId:opts.runId,startedAt:new Date().toISOString(),until:opts.until||null,hours:opts.hours,node:process.execPath,workers:opts.workers,command:[executable,...launchArgs],log});console.log('Started detached run at PID '+child.pid+' · '+opts.workers+' workers · '+log);child.unref();fs.closeSync(fd);});
