#!/usr/bin/env node
'use strict';
const E=require('./evidence.cjs');
const fs=require('node:fs');const {atomic,nextRound}=require('./common.cjs');
function merge(states){if(!states.length)throw Error('Need checkpoints');const pool=states[0].config.poolHash,map=new Map(),hashes=new Set(states.map(s=>s.config.mechanicsHash).filter(Boolean));if(hashes.size>1)throw Error('Merge requires compatible simulator mechanics');if(new Set(states.map(s=>JSON.stringify([s.config.version||'neural-team-search-v1',s.config.meta||null]))).size>1)throw Error('Merge requires matching simulator version and meta');const factor=E.factor(states[0]);let duplicate=0;
 for(const state of states){if(state.config.poolHash!==pool||!state.observations?.length)throw Error('Merge requires the same pool and raw fixture observations');for(const o of state.observations){const key=[E.identity(state,o.team),E.identity(state,o.opponent),o.seed].join('|');if(map.has(key)){if(map.get(key).score!==o.score)throw Error('Seeded duplicate has inconsistent battle outcomes: '+key);duplicate++;}else map.set(key,o);}}
 const observations=[...map.values()],records=new Map();for(const o of observations){const key=E.identity(states[0],o.team),r=records.get(key)||{team:o.team,reward:0,games:0};r.reward+=o.score*factor;r.games+=factor;records.set(key,r);}
 const evaluationEvidence={fixtureSeeds:[...new Set(states.flatMap(s=>s.evaluationEvidence?.fixtureSeeds||[]))],requiresFreshValidationSeed:states.some(s=>s.evaluationEvidence?.requiresFreshValidationSeed)};
 return {...states[0],evaluationEvidence,records:[...records.values()],observations,models:[],pending:null,validations:[],screenResults:[],finalistTeams:[],baselineResults:[],comparisons:{},runtime:null,history:[],battles:observations.length*factor,round:Math.max(...states.map(nextRound)),merged:{inputCheckpoints:states.length,uniqueFixtures:observations.length,deduplicatedFixtures:duplicate,retainedTeams:records.size,counter:'Inherited counter includes unique retained labeled battles; includes explicitly absorbed earlier evaluations; excludes discarded or unabsorbed pilot work'}};
}
if(require.main===module){const [out,...files]=process.argv.slice(2);if(files.length<2)throw Error('node merge.cjs OUTPUT CHECKPOINT1 CHECKPOINT2 …');const s=merge(files.map(f=>JSON.parse(fs.readFileSync(f))));atomic(out,s);console.log(JSON.stringify(s.merged));}
module.exports={merge};
