'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {play,defaults}=require('../engine.cjs');const {fixtures}=require('./common.cjs');
const base=path.resolve(__dirname,'../../includes/pro');
function replay(a,b,seed){const archetypes=require('../vendor/aiArchetypes.json');const ctx=vm.createContext({console:{log(){}},Math:Object.create(Math),host:'localhost',webRoot:'',siteVersion:'training',settings:{colorblindMode:false,hardMovesetLinks:false},$:{ajax(){},getJSON(url,cb){cb(archetypes)},each(items,cb){for(let i=0;i<items.length;i++)if(cb(i,items[i])===false)break;}}});
for(const file of ['GameMaster','DamageCalculator','ActionLogic','TimelineEvent','TimelineAction','DecisionOption','Battle','Pokemon'])vm.runInContext(fs.readFileSync(path.join(base,'vendor',file+'.js'),'utf8'),ctx);
for(const file of ['TrainingAI','Player'])vm.runInContext(fs.readFileSync(path.join(base,'vendor/training',file+'.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(base,'team-replay-runtime.js'),'utf8'),ctx);ctx.input={data:structuredClone(require('../../includes/pro/data/gamemaster.json')),teams:[a,b],policies:[defaults,defaults],cp:1500,seed};return vm.runInContext('replayTeamBattle(input)',ctx);}
test('portable browser replays preserve simulator outcomes, turns and remaining Pokémon on both sides',()=>{const report=require('../../includes/pro/data/team-teams/index.json'),a=report.rows[0].team.map(i=>report.variants[i]);for(const seed of [2507409873,17,551]){const b=report.opponents.slice(0,3);for(const teams of [[a,b],[b,a]]){const original=play(...teams,defaults,defaults,{seed}),replayed=replay(...teams,seed);assert.equal(replayed.score,original.score);assert.equal(replayed.turns,original.turns);assert.deepEqual(Array.from(replayed.remaining),original.remaining);assert.ok(replayed.samples.length>3);assert.equal(replayed.teamStats.length,2);assert.ok(replayed.samples.every(s=>s[2].length===6&&s[2].every(v=>v>=0)));}}});
module.exports={replay};
test('replayed saved finalist fixtures reproduce their stored mirrored scores',()=>{const report=require('../../includes/pro/data/team-teams/index.json');const r=report.rows.find(r=>r.finalist),matched=require('../../includes/pro/data/team-teams/'+r.chunk+'.json')[r.id].test;const fixturesToCheck=[matched.find(m=>m[2]===1),matched.find(m=>m[2]===0)];for(const [ids,seed,score] of fixturesToCheck){const a=r.team.map(i=>report.variants[i]),b=ids.map(i=>report.opponents[i]);assert.equal((replay(a,b,seed).score+1-replay(b,a,seed).score)/2,score);}});
