#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');const {BattlePool,defaultWorkers,availableCores}=require('../pool.cjs');const {defaults,random}=require('../utils.cjs');
const {VERSION,FEATURE_VERSION,digest,mechanicsHash,atomic,options,features,fixtures,teamKey,randomTeam,mutateTeam}=require('./common.cjs');const {Network}=require('./interaction.cjs');const pairwise=require('./interaction.cjs');const {fitParallel}=require('./fit-interaction.cjs');const {prepare}=require('./prepare.cjs');const {generateCandidates,selectCandidates}=require('./propose.cjs');const {predictParallel}=require('./predict.cjs');const {summarize,baselineTeams,compare}=require('./evaluation.cjs');const {writeReport}=require('./report.cjs');
async function search(opts){
 const directory=path.resolve(opts.out),release=require('./lock.cjs').acquire(directory);
 const finish=code=>{const file=path.join(directory,'process.json');try{if(fs.existsSync(file)){const info=JSON.parse(fs.readFileSync(file));if(info.pid===process.pid&&!info.endedAt&&(info.runId||'')===(opts.runId||'')){info.endedAt=new Date().toISOString();info.exitCode=code;atomic(file,info);}}}finally{release();}};
 process.once('exit',finish);let code=0;
 try{return await runSearch(opts);}catch(error){code=1;throw error;}finally{finish(code);process.removeListener('exit',finish);}
}
async function runSearch(opts){
 const validationSeed=opts.validationSeed||opts.seed+900001;if(!Number.isInteger(validationSeed)||validationSeed<1||validationSeed>0xffffffff)throw Error('validation-seed must fit an unsigned 32-bit seed');
 const {out,hours,workers,initialTeams,batchTeams,opponents,validationTeams,validationOpponents,screenTeams,screenOpponents,baselineCount,candidates,epochs,hidden,ensemble,referenceOpponents,seed,rounds}=opts;
 for(const k of ['workers','initialTeams','batchTeams','opponents','validationTeams','validationOpponents','screenTeams','screenOpponents','baselineCount','candidates','epochs','hidden','ensemble','referenceOpponents','seed','rounds'])if(!Number.isInteger(opts[k])||opts[k]<1)throw Error(k+' must be a positive integer');
 if(!Number.isFinite(hours)||hours<=0||workers>availableCores()||initialTeams<8||batchTeams<4||opponents<2||candidates<batchTeams*2)throw Error('Invalid search limits');
 const directory=path.resolve(out);fs.mkdirSync(directory,{recursive:true});
 const poolPath=path.resolve(opts.pool||path.join(directory,'pool.json'));
 let stopped=false;process.on('SIGINT',()=>{stopped=true;console.log('Stopping; active battles will finish, then the neural search will checkpoint.');});process.on('SIGTERM',()=>{stopped=true;});
 let prepared;if(fs.existsSync(poolPath))prepared=JSON.parse(fs.readFileSync(poolPath));else{if(opts.resume)throw Error('Resume requires the original pool.json');prepared=await prepare({workers,out:poolPath});}
 if(prepared.config.version!==VERSION||prepared.config.cp!==1500||prepared.variants.length<3)throw Error('Unsupported pool');
 // Do not allow stale/tampered pool data to silently change a resumed experiment.
 const check={...prepared};delete check.hash;if(digest(check)!==prepared.hash)throw Error('Pool hash mismatch');
 const variants=prepared.variants,config={version:VERSION,algorithm:'interaction-neural-v3',mechanicsHash:mechanicsHash(),features:FEATURE_VERSION,poolHash:prepared.hash,initialTeams,batchTeams,opponents,validationTeams,validationOpponents,screenTeams,screenOpponents,baselineCount,candidates,epochs,hidden,ensemble,referenceOpponents,validationSeed,seed};
 const checkpoint=path.join(directory,'checkpoint.json');let state={config,round:0,battles:0,records:[],observations:[],models:[],history:[],validations:[],screenResults:[],finalistTeams:[],baselineResults:[]};
 if(opts.resume&&opts.warmStart)throw Error('Choose resume or warm-start');
 if(opts.warmStart){const old=JSON.parse(fs.readFileSync(path.resolve(opts.warmStart)));if(old.config.poolHash!==prepared.hash||old.config.seed!==seed||!old.observations?.length)throw Error('Warm-start requires matching pool/seed and raw fixture observations');if(old.evaluationEvidence?.fixtureSeeds?.includes(validationSeed))throw Error('Warm-start includes this evaluation seed; choose a fresh validation-seed');state.evaluationEvidence=old.evaluationEvidence;if(old.config.mechanicsHash&&old.config.mechanicsHash!==config.mechanicsHash)throw Error('Warm-start simulator mechanics differ');if(!old.config.mechanicsHash){state.legacyWarmStart=true;console.log('Warm-start has no code fingerprint; use only locally verified fixture evidence.');}state.records=old.records;state.observations=old.observations;state.battles=old.battles;state.round=old.round;state.warmStart=path.resolve(opts.warmStart);}
 if(opts.resume){state=JSON.parse(fs.readFileSync(checkpoint));if(digest(state.config)!==digest(config))throw Error('Resume requires original search settings and pool; worker count and hours may change');}else if(fs.existsSync(checkpoint))throw Error('Use --resume or a new --out directory');
 const start=Date.now(),deadline=opts.until?Date.parse(opts.until):start+hours*3600000;if(!Number.isFinite(deadline)||deadline<=start)throw Error('until must be a future ISO timestamp');const searchDeadline=start+(deadline-start)*.8;
 const processFile=path.join(directory,'process.json'),processInfo={pid:process.pid,runId:opts.runId||null,startedAt:new Date().toISOString(),workers,endedAt:null};atomic(processFile,processInfo);
 const pool=new BattlePool(workers),startBattleCount=state.battles;state.runtime={pid:process.pid,workers,startedAt:new Date(start).toISOString(),deadline:new Date(deadline).toISOString(),phase:'starting',peakRssMB:0};
 const telemetry=()=>{state.runtime.elapsedSeconds=(Date.now()-start)/1000;state.runtime.newBattles=state.battles-startBattleCount;state.runtime.battlesPerSecond=state.runtime.newBattles/Math.max(1,state.runtime.elapsedSeconds);state.runtime.peakRssMB=Math.max(state.runtime.peakRssMB,process.memoryUsage.rss()/1048576);state.runtime.workerRecycles=pool.recycles;state.runtime.peakWorkerHeapMB=Math.max(state.runtime.peakWorkerHeapMB||0,pool.peakWorkerHeapBytes/1048576);};
 const save=()=>{telemetry();atomic(checkpoint,state);};const records=new Map(state.records.map(r=>[teamKey(r.team),r]));let models=state.models.map(Network.fromJSON),last=Date.now();
 if(prepared.species.some(s=>!s.features))throw Error('Regenerate pool with recommended opponent features');
 const speciesMap=new Map(prepared.species.map(s=>[s.speciesId,s])),ownCache=new Map(),opponentCache=new Map();
 const ownInput=t=>{const k=teamKey(t);if(!ownCache.has(k))ownCache.set(k,features(t,variants));return ownCache.get(k);};
 const opponentInput=ids=>{const k=ids.join(',');if(!opponentCache.has(k))opponentCache.set(k,features([0,1,2],ids.map(id=>speciesMap.get(id))));return opponentCache.get(k);};
 const referenceInputs=fixtures(prepared.species,referenceOpponents,seed+500001).map(c=>opponentInput(c.team.map(r=>r.speciesId)));let referenceLogits=models.length?pairwise.reference(models,referenceInputs):[];
 const predict=x=>pairwise.predict(models,x,referenceLogits);
 const riskScore=r=>{const n=r.games/2,mean=(r.reward/2+4)/(n+8);return mean-1.28*Math.sqrt(mean*(1-mean)/(n+9));};
 const scoreRecords=()=>[...records.values()].map(r=>({...r,score:r.reward/r.games,selectionScore:riskScore(r)})).sort((a,b)=>b.selectionScore-a.selectionScore||b.games-a.games);
 async function fit(){
  state.runtime.phase='fitting';telemetry();
  const heldoutKey=k=>parseInt(digest(k).slice(0,8),16)%5===0;
  const all=state.observations.map(o=>({a:ownInput(o.team),b:opponentInput(o.opponent),y:o.score,key:teamKey(o.team)}));
  const heldout=all.filter(s=>heldoutKey(s.key)),training=all.filter(s=>!heldoutKey(s.key));if(training.length<16)return null;
  const r=random(seed+state.round*71),sample=training.length<=12000?training:Array.from({length:12000},()=>training[Math.floor(r()*training.length)]);
  const fitStart=Date.now();console.log('Fitting pairwise neural ensemble · '+sample.length+' labeled fixtures · '+workers+' workers / '+ensemble+' models');
  models=await fitParallel(sample,{workers,size:ensemble,hidden,epochs,seed:seed+state.round*173});state.models=models.map(n=>n.toJSON());referenceLogits=pairwise.reference(models,referenceInputs);
  const average=training.reduce((s,r)=>s+r.y,0)/training.length;
  const cached=models.map(()=>new Map()),value=(i,x)=>{if(!cached[i].has(x))cached[i].set(x,models[i].forward(x));return cached[i].get(x);};
  let neuralPairMSE=0,constantPairMSE=0;for(const row of heldout){const prediction=models.reduce((sum,n,i)=>sum+1/(1+Math.exp(-pairwise.logit(n,value(i,row.a),value(i,row.b)))),0)/models.length;neuralPairMSE+=(prediction-row.y)**2;constantPairMSE+=(average-row.y)**2;}
  const measured=[...records.values()].filter(r=>heldoutKey(teamKey(r.team)));const avg=measured.reduce((sum,r)=>sum+r.reward/r.games,0)/Math.max(1,measured.length);
  return {trainingFixtures:training.length,heldoutFixtures:heldout.length,heldoutTeams:measured.length,neuralPairMSE:heldout.length?neuralPairMSE/heldout.length:null,constantPairMSE:heldout.length?constantPairMSE/heldout.length:null,neuralMSE:measured.length?measured.reduce((sum,r)=>sum+(predict(ownInput(r.team)).mean-r.reward/r.games)**2,0)/measured.length:null,constantMSE:measured.length?measured.reduce((sum,r)=>sum+(average-r.reward/r.games)**2,0)/measured.length:null,heldoutMean:avg,fitSeconds:(Date.now()-fitStart)/1000};
 }
 async function propose(){const params={variants,known:scoreRecords().slice(0,24),seen:records,seed:seed+state.round*7919,candidates,batchTeams},generation=generateCandidates(params);const scores=models.length?await predictParallel(generation.teams.map(t=>features(t,variants)),models,referenceLogits,{workers:generation.teams.length<64?1:workers}):generation.teams.map(()=>({mean:.5,uncertainty:0}));return selectCandidates(params,generation,scores);}
 async function evaluate(teams,cases,limit,onTeam=()=>{}){
  const jobs=[];for(const team of teams){const own=team.map(i=>variants[i]);for(const c of cases){jobs.push([own,c.team,defaults,defaults,{seed:c.seed,cp:1500}],[c.team,own,defaults,defaults,{seed:c.seed,cp:1500}]);}}
  const perTeam=cases.length*2,partial=teams.map(()=>new Array(perTeam)),counts=teams.map(()=>0);let done=0;const results=await pool.map(jobs,{shouldStop:()=>stopped||Date.now()>=limit,onResult:(r,index)=>{state.battles++;done++;state.runtime.peakRssMB=Math.max(state.runtime.peakRssMB,process.memoryUsage.rss()/1048576);if(r.timedOut)throw Error('Battle timeout: no fabricated draw accepted');const ti=Math.floor(index/perTeam),si=index%perTeam;partial[ti][si]=si%2?1-r.score:r.score;if(++counts[ti]===perTeam)onTeam({team:teams[ti],scores:partial[ti]});if(Date.now()-last>10000){last=Date.now();console.log('[team-search] '+state.battles+' battles · '+records.size+' labeled teams · '+workers+' workers · RSS '+Math.round(process.memoryUsage().rss/1048576)+' MB · batch '+done+'/'+jobs.length);}}});
  if(!results)return null;const n=cases.length*2;return teams.map((team,i)=>({team,scores:results.slice(i*n,(i+1)*n).map((r,j)=>j%2?1-r.score:r.score)}));
 }
 function recommendations(){const ordered=scoreRecords(),byKey=new Map(ordered.map(r=>[teamKey(r.team),r])),finalists=(state.finalistTeams||[]).map(t=>byKey.get(teamKey(t))).filter(Boolean),rest=ordered.filter(r=>!finalists.some(f=>teamKey(f.team)===teamKey(r.team)));return [...finalists,...rest].slice(0,20).map(r=>({team:r.team.map(i=>({speciesId:variants[i].speciesId,speciesName:variants[i].speciesName,types:variants[i].types,moveset:variants[i].moveset,ivs:variants[i].ivs,cp:variants[i].cp,level:variants[i].level})),variantIndices:r.team,trainingScore:r.score,trainingGames:r.games,selectionScore:r.selectionScore,screen:state.screenResults?.find(s=>teamKey(s.team)===teamKey(r.team))||null,neural:models.length?predict(ownInput(r.team)):null,validation:state.validations.find(v=>teamKey(v.team)===teamKey(r.team))||null}));}
 try{
  save();if(!models.length&&state.observations.length)await fit();console.log('Neural team search · '+prepared.species.length+' species / '+variants.length+' movesets · '+workers+' workers · stop by '+new Date(deadline).toLocaleString());
  while(!stopped&&Date.now()<searchDeadline&&state.round<rounds){
   state.runtime.phase='searching';
   if(!state.pending){const proposed=state.round===0?{teams:Array.from({length:initialTeams},(_,i)=>randomTeam(variants,random(seed+i*397))),sources:{}}:await propose();state.pending={round:state.round,teams:[...new Map(proposed.teams.map(t=>[teamKey(t),t])).values()],sources:proposed.sources,results:[],completed:[]};save();}
   if(state.pending.round!==state.round)throw Error('Pending round mismatch');const teams=state.pending.teams.filter(t=>!state.pending.completed.includes(teamKey(t)));
   const cases=fixtures(prepared.species,opponents,seed+400001+state.round*104729);
   const evaluated=await evaluate(teams,cases,searchDeadline,e=>{const key=teamKey(e.team),old=records.get(key)||{team:e.team,reward:0,games:0};old.reward+=e.scores.reduce((a,b)=>a+b,0);old.games+=e.scores.length;records.set(key,old);for(let i=0;i<cases.length;i++)state.observations.push({team:e.team,opponent:cases[i].team.map(r=>r.speciesId),score:(e.scores[i*2]+e.scores[i*2+1])/2,seed:cases[i].seed,round:state.round,source:state.pending.sources?.[key]||'initial'});state.pending.results.push({source:state.pending.sources?.[key]||'initial',score:e.scores.reduce((a,b)=>a+b,0)/e.scores.length});state.pending.completed.push(key);state.records=[...records.values()];save();});if(!evaluated)break;
   const grouped=new Map();for(const r of state.pending.results){const g=grouped.get(r.source)||{source:r.source,teams:0,sum:0};g.teams++;g.sum+=r.score;grouped.set(r.source,g);}const proposalScores=[...grouped.values()].map(g=>({source:g.source,teams:g.teams,meanScore:g.sum/g.teams}));state.pending=null;state.round++;state.records=[...records.values()];const diagnostics=await fit();const summary={round:state.round,battles:state.battles,teams:records.size,bestTraining:scoreRecords()[0].score,proposalScores,diagnostics,elapsedSeconds:(Date.now()-start)/1000};state.history.push(summary);fs.appendFileSync(path.join(directory,'history.jsonl'),JSON.stringify({...summary,timestamp:new Date().toISOString()})+'\n');save();console.log(JSON.stringify(summary));
  }
  if(!stopped&&!models.length&&records.size>=8)await fit();
  // Independent opponent fixtures never enter neural fitting or candidate generation.
  if(!stopped&&records.size&&Date.now()<deadline){
   state.runtime.phase='screening';console.log('Screening training leaders on fresh weighted opponent teams…');state.screenResults=[];const screening=fixtures(prepared.species,screenOpponents,seed+600001),screenCandidates=scoreRecords().slice(0,screenTeams).map(r=>r.team);
   const screeningLimit=Date.now()+(deadline-Date.now())*.5;
   for(const team of screenCandidates){const evaluated=await evaluate([team],screening,screeningLimit);if(!evaluated)break;state.screenResults.push(summarize(evaluated[0].scores,{team,fixtureSeed:seed+600001,kind:'screening'}));save();console.log('Screened '+state.screenResults.length+'/'+screenCandidates.length);}
   const screened=state.screenResults.slice().sort((a,b)=>b.score-a.score);state.finalistTeams=screened.slice(0,validationTeams).map(r=>r.team);if(!state.finalistTeams.length)state.finalistTeams=scoreRecords().slice(0,validationTeams).map(r=>r.team);save();
   state.runtime.phase='validating';console.log('Validating screened finalists against untouched opponent teams…');const teams=state.finalistTeams,cases=fixtures(prepared.species,validationOpponents,validationSeed);state.validations=[];
   // Save each finalist separately; budget expiration need not discard other complete validations.
   for(const team of teams){const evaluated=await evaluate([team],cases,deadline);if(!evaluated)break;state.validations.push(summarize(evaluated[0].scores,{team,fixtureSeed:validationSeed}));save();console.log('Validated '+state.validations.length+'/'+teams.length+' · score '+(state.validations.at(-1).score*100).toFixed(1)+'%');}
   state.runtime.phase='baselines';state.baselineResults=[];const baseline=baselineTeams(prepared,baselineCount,seed+700001);
   for(const entry of baseline){if(stopped||Date.now()>=deadline)break;const evaluated=await evaluate([entry.team],cases,deadline);if(!evaluated)break;state.baselineResults.push(summarize(evaluated[0].scores,{...entry,fixtureSeed:validationSeed}));save();console.log('Validated baseline '+state.baselineResults.length+'/'+baseline.length+' · '+entry.kind);}
   state.comparisons={};for(const kind of ['uniform-random','weight-sampled-best-moves','greedy-scout-coverage']){const rows=state.baselineResults.filter(b=>b.kind===kind);if(rows.length&&state.validations.length)state.comparisons[kind]=compare(state.validations[0],rows,{seed:seed+800001});}save();

  }
 }catch(error){state.runtime.error=error.message;throw error;}finally{try{state.runtime.phase=state.runtime.error?'failed':stopped?'stopped':'finished';state.records=[...records.values()];save();const report={version:VERSION,poolHash:prepared.hash,rounds:state.round,battles:state.battles,baselineResults:state.baselineResults,comparisons:state.comparisons,warning:'Experimental Champion-controlled simulation. Training-selected finalists; no optimality or real usage guarantee. Ensemble disagreement is not a calibrated confidence interval.',rows:recommendations()};atomic(path.join(directory,'recommendations.json'),report);writeReport(directory,state,prepared,report);atomic(path.join(directory,'models.json'),state.models);console.log('Saved '+checkpoint+' and recommendations.json');}finally{await pool.close();}}
}
if(require.main===module){const opts=options(process.argv.slice(2),{hours:6,workers:defaultWorkers(),initialTeams:128,batchTeams:24,opponents:64,validationTeams:8,validationOpponents:512,screenTeams:24,screenOpponents:512,baselineCount:12,candidates:12000,epochs:6,hidden:16,ensemble:12,referenceOpponents:256,validationSeed:0,seed:20261009,rounds:1000000,out:'training/runs/team-search',pool:'',warmStart:'',until:'',runId:'',resume:false});if(opts.help)console.log('node training/team-search/search.cjs [--hours 6] [--until ISO-TIMESTAMP] [--resume] [--workers N] [--out DIR] [--pool FILE] [--warm-start CHECKPOINT] [--initial-teams 128] [--batch-teams 24] [--opponents 64] [--validation-teams 8] [--validation-opponents 512] [--screen-teams 24] [--screen-opponents 512] [--baseline-count 12] [--candidates 12000] [--epochs 6] [--hidden 16] [--ensemble 12] [--reference-opponents 256] [--validation-seed N] [--rounds N] [--seed N]');else search(opts).catch(e=>{console.error(e);process.exitCode=1;});}
module.exports={search};
