#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');const {BattlePool,defaultWorkers,availableCores}=require('../pool.cjs');const {BattleRunner}=require('../runner.cjs');const {createMeta}=require('./meta.cjs');const {defaults,random}=require('../utils.cjs');
const {VERSION,FEATURE_VERSION,digest,mechanicsHash,dataHash,algorithmHash,screeningSeed,freshEvaluationSeeds,nextRound,sampleFixtures,atomic,options,features,fixtures,teamKey,randomTeam}=require('./common.cjs');const {Network}=require('./interaction.cjs');const pairwise=require('./interaction.cjs');const {fitParallel}=require('./fit-interaction.cjs');const {prepare}=require('./prepare.cjs');const {generateCandidates,selectCandidates}=require('./propose.cjs');const {predictParallel}=require('./predict.cjs');const {summarize,panelIndex,commonPanelScores,baselineTeams,compare,compareFinalists}=require('./evaluation.cjs');const {writeReport}=require('./report.cjs');const {trainingBudget}=require('./budget.cjs');
async function search(opts){
 const directory=path.resolve(opts.out),release=require('./lock.cjs').acquire(directory);
 const finish=code=>{const file=path.join(directory,'process.json');try{if(fs.existsSync(file)){const info=JSON.parse(fs.readFileSync(file));if(info.pid===process.pid&&!info.endedAt&&(info.runId||'')===(opts.runId||'')){info.endedAt=new Date().toISOString();info.exitCode=code;atomic(file,info);}}}finally{release();}};
 process.once('exit',finish);let code=0;
 try{return await runSearch(opts);}catch(error){code=1;throw error;}finally{finish(code);process.removeListener('exit',finish);}
}
async function runSearch(opts){
 const validationSeed=opts.validationSeed||opts.seed+900001;if(!Number.isInteger(validationSeed)||validationSeed<1||validationSeed>0xffffffff)throw Error('validation-seed must fit an unsigned 32-bit seed');
 const screenSeed=screeningSeed(validationSeed);
 const {out,hours,workers,initialTeams,batchTeams,opponents,validationTeams,validationOpponents,screenTeams,screenOpponents,baselineCount,candidates,epochs,hidden,ensemble,referenceOpponents,fitFixtures,seed,rounds}=opts;
 for(const k of ['workers','initialTeams','batchTeams','opponents','validationTeams','validationOpponents','screenTeams','screenOpponents','baselineCount','candidates','epochs','hidden','ensemble','referenceOpponents','fitFixtures','seed','rounds'])if(!Number.isInteger(opts[k])||opts[k]<1)throw Error(k+' must be a positive integer');
 if(!Number.isInteger(opts.lookaheadTurns??24)||(opts.lookaheadTurns??24)<4||(opts.lookaheadTurns??24)>120||!Number.isInteger(opts.decisionInterval??4)||(opts.decisionInterval??4)<1)throw Error('Lookahead turns must be 4–120; decision interval must be a positive integer');
 if(!Number.isFinite(hours)||hours<=0||workers>availableCores()||initialTeams<8||batchTeams<4||opponents<2||candidates<batchTeams*2)throw Error('Invalid search limits');
 const directory=path.resolve(out);fs.mkdirSync(directory,{recursive:true});
 const poolPath=path.resolve(opts.pool||path.join(directory,'pool.json'));
 let stopped=false;process.on('SIGINT',()=>{stopped=true;console.log('Stopping; active battles will finish, then the neural search will checkpoint.');});process.on('SIGTERM',()=>{stopped=true;});
 let prepared;if(fs.existsSync(poolPath))prepared=JSON.parse(fs.readFileSync(poolPath));else{if(opts.resume)throw Error('Resume requires the original pool.json');prepared=await prepare({workers,out:poolPath});}
 if(![VERSION,'neural-team-search-v2','neural-team-search-v1'].includes(prepared.config.version)||prepared.config.cp!==1500||prepared.variants.length<3)throw Error('Unsupported pool');
 // Do not allow stale/tampered pool data to silently change a resumed experiment.
 const check={...prepared};delete check.hash;if(digest(check)!==prepared.hash)throw Error('Pool hash mismatch');
 if(prepared.config.inputHash!==dataHash())throw Error('Pool data differs from bundled rankings, weights or Game Master; regenerate the pool');
 if(path.resolve(poolPath)!==path.join(directory,'pool.json'))fs.copyFileSync(poolPath,path.join(directory,'pool.json'));
 const meta=createMeta(prepared.species,{mode:opts.meta||'hybrid',usageFile:opts.usageFile||'',weightPower:opts.metaWeightPower??1.25,halfLifeDays:opts.usageHalfLifeDays??0,asOf:opts.usageAsOf||'',priorStrength:opts.usagePriorStrength??500}),fixtures=(_species,n,seed)=>{const rows=meta.fixtures(n,seed);if(seed===screenSeed||seed===validationSeed){state.fixturePanels??={};state.fixturePanels[seed]=rows;}return rows;};
 const variants=prepared.variants,config={version:VERSION,algorithm:'interaction-neural-v5-common-panel',meta:meta.description,lookaheadTurns:opts.lookaheadTurns||24,decisionInterval:opts.decisionInterval||4,algorithmHash:algorithmHash(),mechanicsHash:mechanicsHash(),features:FEATURE_VERSION,poolHash:prepared.hash,initialTeams,batchTeams,opponents,validationTeams,validationOpponents,screenTeams,screenOpponents,baselineCount,candidates,epochs,hidden,ensemble,referenceOpponents,fitFixtures,validationSeed,screenSeed,seed};
 const checkpoint=path.join(directory,'checkpoint.json');let state={config,round:0,battles:0,records:[],observations:[],models:[],history:[],validations:[],screenResults:[],finalistTeams:[],baselineResults:[]};
 if(opts.resume&&opts.warmStart)throw Error('Choose resume or warm-start');
 if(opts.warmStart){const old=JSON.parse(fs.readFileSync(path.resolve(opts.warmStart)));if(old.config.version!==VERSION||old.config.mechanicsHash!==config.mechanicsHash||digest(old.config.meta)!==digest(config.meta))throw Error('Warm-start requires the same simulator version, mechanics and meta; keep historical runs separate');if(old.config.poolHash!==prepared.hash||old.config.seed!==seed||!old.observations?.length)throw Error('Warm-start requires matching pool/seed and raw fixture observations');if(!freshEvaluationSeeds(validationSeed,old.evaluationEvidence?.fixtureSeeds))throw Error('Warm-start includes an evaluation seed; choose a fresh validation-seed');state.evaluationEvidence=old.evaluationEvidence;if(old.config.mechanicsHash&&old.config.mechanicsHash!==config.mechanicsHash)throw Error('Warm-start simulator mechanics differ');if(!old.config.mechanicsHash){state.legacyWarmStart=true;console.log('Warm-start has no code fingerprint; use only locally verified fixture evidence.');}state.records=old.records;state.observations=old.observations;state.battles=old.battles;state.round=nextRound(old);state.warmStart=path.resolve(opts.warmStart);}
 if(opts.resume){state=JSON.parse(fs.readFileSync(checkpoint));if(digest(state.config)!==digest(config))throw Error('Resume requires original algorithm code, settings and pool; worker count and hours may change. Use warm-start with a new directory after algorithm changes');}else if(fs.existsSync(checkpoint))throw Error('Use --resume or a new --out directory');
 const start=Date.now(),deadline=opts.until?Date.parse(opts.until):start+hours*3600000;if(!Number.isFinite(deadline)||deadline<=start)throw Error('until must be a future ISO timestamp');const fixedSearchDeadline=start+(deadline-start)*.8;let searchDeadline=fixedSearchDeadline;
 const processFile=path.join(directory,'process.json'),processInfo={pid:process.pid,runId:opts.runId||null,startedAt:new Date().toISOString(),workers,endedAt:null};atomic(processFile,processInfo);
 const pool=new BattlePool(workers,()=>new BattleRunner({workerFile:path.join(__dirname,'../battle-worker-v2.cjs'),heapMb:192})),startBattleCount=state.battles,startCpu=process.cpuUsage();state.runtime={pid:process.pid,workers,startedAt:new Date(start).toISOString(),deadline:new Date(deadline).toISOString(),phase:'starting',peakRssMB:0};
 const telemetry=()=>{state.runtime.elapsedSeconds=(Date.now()-start)/1000;state.runtime.newBattles=state.battles-startBattleCount;const cpu=process.cpuUsage(startCpu);state.runtime.cpuSeconds=(cpu.user+cpu.system)/1000000;state.runtime.averageCoresUsed=state.runtime.cpuSeconds/Math.max(.001,state.runtime.elapsedSeconds);state.runtime.battlesPerSecond=state.runtime.newBattles/Math.max(1,state.runtime.elapsedSeconds);state.runtime.peakRssMB=Math.max(state.runtime.peakRssMB,process.memoryUsage.rss()/1048576);state.runtime.workerRecycles=pool.recycles;state.runtime.peakWorkerHeapMB=Math.max(state.runtime.peakWorkerHeapMB||0,pool.peakWorkerHeapBytes/1048576);};
 const updateBudget=()=>{const budget=trainingBudget({start,deadline,now:Date.now(),newBattles:state.battles-startBattleCount,battlesPerFixture:1,screenTeams,screenOpponents,validationTeams,validationOpponents,baselineCount});searchDeadline=budget.deadline;state.runtime.trainingDeadline=new Date(searchDeadline).toISOString();state.runtime.estimatedEvaluationSeconds=budget.estimatedEvaluationSeconds;return searchDeadline;};
 const save=()=>{telemetry();atomic(checkpoint,state);};const fixtureCounts=new Map();for(const observation of state.observations){const key=teamKey(observation.team);fixtureCounts.set(key,(fixtureCounts.get(key)||0)+1);}const records=new Map(state.records.map(r=>[teamKey(r.team),{...r,fixtures:fixtureCounts.get(teamKey(r.team))||r.fixtures||r.games}]));let models=state.models.map(Network.fromJSON),last=Date.now();
 if(prepared.species.some(s=>!s.features))throw Error('Regenerate pool with recommended opponent features');
 const speciesMap=new Map(prepared.species.map(s=>[s.speciesId,s])),ownCache=new Map(),opponentCache=new Map();
 const ownInput=t=>{const k=teamKey(t);if(!ownCache.has(k))ownCache.set(k,features(t,variants));return ownCache.get(k);};
 const opponentInput=ids=>{const k=ids.join(',');if(!opponentCache.has(k))opponentCache.set(k,features([0,1,2],ids.map(id=>speciesMap.get(id))));return opponentCache.get(k);};
 const referenceInputs=fixtures(prepared.species,referenceOpponents,seed+500001).map(c=>opponentInput(c.team.map(r=>r.speciesId)));let referenceLogits=models.length?pairwise.reference(models,referenceInputs):[];
 const predict=x=>pairwise.predict(models,x,referenceLogits);
 // Mirrored legacy battles share an opponent fixture. Count that fixture once
 // when estimating sampling risk; do not mistake two orientations for two draws.
 const riskScore=r=>{const n=r.fixtures||r.games,mean=(r.reward/r.games*n+4)/(n+8);return mean-1.28*Math.sqrt(mean*(1-mean)/(n+9));};
 const scoreRecords=()=>[...records.values()].map(r=>({...r,score:r.reward/r.games,selectionScore:riskScore(r)})).sort((a,b)=>b.selectionScore-a.selectionScore||b.games-a.games);
 async function fit(){
  state.runtime.phase='fitting';telemetry();
  const heldoutKey=k=>parseInt(digest(k).slice(0,8),16)%5===0;
  const all=state.observations.map(o=>({a:ownInput(o.team),b:opponentInput(o.opponent),y:o.score,key:teamKey(o.team)}));
  const heldout=all.filter(s=>heldoutKey(s.key)),training=all.filter(s=>!heldoutKey(s.key));if(training.length<16)return null;
  const r=random(seed+state.round*71),sample=sampleFixtures(training,fitFixtures,r);
  const fitStart=Date.now();console.log('Fitting pairwise neural ensemble · '+sample.length+' labeled fixtures · '+workers+' workers / '+ensemble+' models');
  models=await fitParallel(sample,{workers,size:ensemble,hidden,epochs,seed:seed+state.round*173});state.models=models.map(n=>n.toJSON());referenceLogits=pairwise.reference(models,referenceInputs);
  const average=training.reduce((s,r)=>s+r.y,0)/training.length;
  const cached=models.map(()=>new Map()),value=(i,x)=>{if(!cached[i].has(x))cached[i].set(x,models[i].forward(x));return cached[i].get(x);};
  let neuralPairMSE=0,constantPairMSE=0;for(const row of heldout){const prediction=models.reduce((sum,n,i)=>sum+1/(1+Math.exp(-pairwise.logit(n,value(i,row.a),value(i,row.b)))),0)/models.length;neuralPairMSE+=(prediction-row.y)**2;constantPairMSE+=(average-row.y)**2;}
  const measured=[...records.values()].filter(r=>heldoutKey(teamKey(r.team)));const avg=measured.reduce((sum,r)=>sum+r.reward/r.games,0)/Math.max(1,measured.length);
  const diagnostics={fitFixtures:sample.length,trainingFixtures:training.length,heldoutFixtures:heldout.length,heldoutTeams:measured.length,neuralPairMSE:heldout.length?neuralPairMSE/heldout.length:null,constantPairMSE:heldout.length?constantPairMSE/heldout.length:null,neuralMSE:measured.length?measured.reduce((sum,r)=>sum+(predict(ownInput(r.team)).mean-r.reward/r.games)**2,0)/measured.length:null,constantMSE:measured.length?measured.reduce((sum,r)=>sum+(average-r.reward/r.games)**2,0)/measured.length:null,heldoutMean:avg,fitSeconds:(Date.now()-fitStart)/1000};state.latestDiagnostics=diagnostics;return diagnostics;
 }
 async function propose(){const params={variants,known:scoreRecords().slice(0,24),seen:records,seed:seed+state.round*7919,candidates,batchTeams},generation=generateCandidates(params);const scores=models.length?await predictParallel(generation.teams.map(t=>features(t,variants)),models,referenceLogits,{workers:generation.teams.length<64?1:workers}):generation.teams.map(()=>({mean:.5,uncertainty:0}));return selectCandidates(params,generation,scores);}
 async function evaluate(teams,cases,limit,onTeam=()=>{},{commonPanel=false}={}){
  if(!teams.length||!cases.length)return [];
  const own=teams.map(team=>team.map(i=>variants[i])),jobs=[],job=(ti,si)=>[own[ti],cases[si].team,defaults,defaults,{seed:cases[si].seed,cp:1500,horizon:opts.lookaheadTurns||24,interval:opts.decisionInterval||4}];
  if(commonPanel){for(let si=0;si<cases.length;si++)for(let ti=0;ti<teams.length;ti++)jobs.push(job(ti,si));}
  else{for(let ti=0;ti<teams.length;ti++)for(let si=0;si<cases.length;si++)jobs.push(job(ti,si));}
  const perTeam=cases.length,partial=teams.map(()=>new Array(perTeam)),counts=teams.map(()=>0);let done=0;const results=await pool.map(jobs,{shouldStop:()=>stopped||Date.now()>=(typeof limit==='function'?limit():limit),onResult:(r,index)=>{state.battles++;done++;state.runtime.peakRssMB=Math.max(state.runtime.peakRssMB,process.memoryUsage.rss()/1048576);if(r.timedOut)throw Error('Battle timeout: no fabricated draw accepted');if(!Number.isFinite(r.score)||r.score<0||r.score>1)throw Error('Invalid battle score');const position=commonPanel?panelIndex(index,teams.length):{team:Math.floor(index/perTeam),fixture:index%perTeam},ti=position.team,si=position.fixture;partial[ti][si]=r.score;if(++counts[ti]===perTeam)onTeam({team:teams[ti],scores:partial[ti]});if(Date.now()-last>10000){last=Date.now();console.log('[team-search] '+state.battles+' battles · '+records.size+' labeled teams · '+workers+' workers · RSS '+Math.round(process.memoryUsage().rss/1048576)+' MB · batch '+done+'/'+jobs.length);}}});
  if(commonPanel)return commonPanelScores(teams,partial);
  return results?teams.map((team,i)=>({team,scores:partial[i]})):null;
 }
 function recommendations(){const ordered=scoreRecords(),byKey=new Map(ordered.map(r=>[teamKey(r.team),r])),finalists=(state.finalistTeams||[]).map(t=>byKey.get(teamKey(t))).filter(Boolean),rest=ordered.filter(r=>!finalists.some(f=>teamKey(f.team)===teamKey(r.team)));return [...finalists,...rest].slice(0,20).map(r=>({team:r.team.map(i=>({speciesId:variants[i].speciesId,speciesName:variants[i].speciesName,types:variants[i].types,moveset:variants[i].moveset,ivs:variants[i].ivs,cp:variants[i].cp,level:variants[i].level})),variantIndices:r.team,trainingScore:r.score,trainingGames:r.games,selectionScore:r.selectionScore,screen:state.screenResults?.find(s=>teamKey(s.team)===teamKey(r.team))||null,neural:models.length?predict(ownInput(r.team)):null,validation:state.validations.find(v=>teamKey(v.team)===teamKey(r.team))||null}));}
 try{
  save();if(!models.length&&state.observations.length)await fit();console.log('Neural team search · '+prepared.species.length+' species / '+variants.length+' movesets · '+workers+' workers · stop by '+new Date(deadline).toLocaleString());
  while(!stopped&&Date.now()<fixedSearchDeadline&&state.round<rounds){
   if(Date.now()>=updateBudget())break;
   state.runtime.phase='searching';
   if(!state.pending){const proposed=state.round===0?{teams:Array.from({length:initialTeams},(_,i)=>randomTeam(variants,random(seed+i*397))),sources:{}}:await propose();state.pending={round:state.round,teams:[...new Map(proposed.teams.map(t=>[teamKey(t),t])).values()],sources:proposed.sources,results:[],completed:[]};save();}
   if(state.pending.round!==state.round)throw Error('Pending round mismatch');const teams=state.pending.teams.filter(t=>!state.pending.completed.includes(teamKey(t)));
   const cases=fixtures(prepared.species,opponents,seed+400001+state.round*104729);
   const evaluated=await evaluate(teams,cases,updateBudget,e=>{const key=teamKey(e.team),old=records.get(key)||{team:e.team,reward:0,games:0,fixtures:0};old.reward+=e.scores.reduce((a,b)=>a+b,0);old.games+=e.scores.length;old.fixtures+=e.scores.length;records.set(key,old);for(let i=0;i<cases.length;i++)state.observations.push({team:e.team,opponent:cases[i].team.map(r=>r.speciesId),score:e.scores[i],seed:cases[i].seed,round:state.round,source:state.pending.sources?.[key]||'initial'});state.pending.results.push({source:state.pending.sources?.[key]||'initial',score:e.scores.reduce((a,b)=>a+b,0)/e.scores.length});state.pending.completed.push(key);state.records=[...records.values()];save();});if(!evaluated)break;
   const grouped=new Map();for(const r of state.pending.results){const g=grouped.get(r.source)||{source:r.source,teams:0,sum:0};g.teams++;g.sum+=r.score;grouped.set(r.source,g);}const proposalScores=[...grouped.values()].map(g=>({source:g.source,teams:g.teams,meanScore:g.sum/g.teams}));state.pending=null;state.round++;state.records=[...records.values()];const diagnostics=await fit();const summary={round:state.round,battles:state.battles,teams:records.size,bestTraining:scoreRecords()[0].score,proposalScores,diagnostics,elapsedSeconds:(Date.now()-start)/1000};state.history.push(summary);fs.appendFileSync(path.join(directory,'history.jsonl'),JSON.stringify({...summary,timestamp:new Date().toISOString()})+'\n');save();console.log(JSON.stringify(summary));
  }
  if(!stopped&&!models.length&&records.size>=8)await fit();
  // Independent opponent fixtures never enter neural fitting or candidate generation.
  if(!stopped&&records.size&&Date.now()<deadline){
   state.runtime.phase='screening';console.log('Screening training leaders on fresh meta opponent teams…');state.screenResults=[];const screening=fixtures(prepared.species,screenOpponents,screenSeed),screenCandidates=scoreRecords().slice(0,screenTeams).map(r=>r.team);
   const screenWork=screenCandidates.length*screening.length,finalWork=(validationTeams+baselineCount)*validationOpponents,screeningLimit=Date.now()+(deadline-Date.now())*screenWork/(screenWork+finalWork);
   const screeningRows=await evaluate(screenCandidates,screening,screeningLimit,()=>{},{commonPanel:true});state.screenResults=screeningRows.map(row=>summarize(row.scores,{team:row.team,fixtureSeed:screenSeed,kind:'screening',paired:false}));state.screenPanel={requestedFixtures:screening.length,completedFixtures:screeningRows[0]?.scores.length||0,teams:screenCandidates.length};save();console.log('Screened '+state.screenResults.length+' teams on '+state.screenPanel.completedFixtures+'/'+screening.length+' common fixtures');
   const screened=state.screenResults.slice().sort((a,b)=>b.score-a.score);state.finalistTeams=screened.slice(0,validationTeams).map(r=>r.team);if(!state.finalistTeams.length)state.finalistTeams=scoreRecords().slice(0,validationTeams).map(r=>r.team);save();
   state.runtime.phase='validating';console.log('Validating screened finalists against untouched meta opponent teams…');const teams=state.finalistTeams,cases=fixtures(prepared.species,validationOpponents,validationSeed);state.validations=[];
   // Interleave finalists AND baselines by opponent fixture. If time expires,
   // every score uses the same completed prefix rather than favoring early teams.
   const baseline=baselineTeams(prepared,baselineCount,seed+700001),panelTeams=[...new Map([...teams,...baseline.map(b=>b.team)].map(t=>[teamKey(t),t])).values()],evaluated=await evaluate(panelTeams,cases,deadline,()=>{},{commonPanel:true}),byTeam=new Map(evaluated.map(row=>[teamKey(row.team),row]));
   state.validations=teams.map(team=>{const row=byTeam.get(teamKey(team));return row?summarize(row.scores,{team,fixtureSeed:validationSeed,paired:false}):null;}).filter(Boolean);
   state.baselineResults=baseline.map(entry=>{const row=byTeam.get(teamKey(entry.team));return row?summarize(row.scores,{...entry,fixtureSeed:validationSeed,paired:false}):null;}).filter(Boolean);
   state.finalPanel={requestedFixtures:cases.length,completedFixtures:evaluated[0]?.scores.length||0,teams:panelTeams.length,complete:(evaluated[0]?.scores.length||0)===cases.length};
   console.log('Validated '+state.validations.length+' finalists and '+state.baselineResults.length+' baselines on '+state.finalPanel.completedFixtures+'/'+cases.length+' common fixtures');
   state.comparisons={};for(const kind of ['uniform-random','weight-sampled-best-moves','greedy-scout-coverage']){const rows=state.baselineResults.filter(b=>b.kind===kind);if(rows.length&&state.validations.length)state.comparisons[kind]=compare(state.validations[0],rows,{seed:seed+800001});}
   state.finalistComparisons=compareFinalists(state.validations[0],state.validations.slice(1),{seed:seed+800002});save();

  }
 }catch(error){state.runtime.error=error.message;throw error;}finally{try{state.runtime.phase=state.runtime.error?'failed':stopped?'stopped':'finished';state.records=[...records.values()];save();const report={version:VERSION,poolHash:prepared.hash,rounds:state.round,battles:state.battles,baselineResults:state.baselineResults,comparisons:state.comparisons,finalPanel:state.finalPanel,finalistComparisons:state.finalistComparisons,warning:'Experimental bounded-lookahead/Champion-controlled simulation. Training-selected finalists; no optimality or real usage guarantee. Ensemble disagreement is not a calibrated confidence interval.',rows:recommendations()};atomic(path.join(directory,'recommendations.json'),report);writeReport(directory,state,prepared,report);try{const bundle=require('./export-report.cjs').writeReportBundle(state,prepared,path.join(directory,'report.pvpteams.json.gz'));console.log('UI report: '+bundle.out+' ('+bundle.bytes+' bytes)');}catch(exportError){console.error('UI report export failed: '+exportError.message);}atomic(path.join(directory,'models.json'),state.models);console.log('Saved '+checkpoint+' and recommendations.json');}finally{await pool.close();}}
}
if(require.main===module){const opts=options(process.argv.slice(2),{hours:6,workers:defaultWorkers(),initialTeams:128,batchTeams:24,opponents:64,validationTeams:8,validationOpponents:512,screenTeams:24,screenOpponents:512,baselineCount:12,candidates:12000,epochs:6,hidden:16,ensemble:12,referenceOpponents:256,fitFixtures:48000,validationSeed:0,seed:20261009,rounds:1000000,out:'training/runs/team-search-v3',pool:'',meta:'hybrid',usageFile:'',lookaheadTurns:24,decisionInterval:4,metaWeightPower:1.25,usageHalfLifeDays:0,usageAsOf:'',usagePriorStrength:500,warmStart:'',until:'',runId:'',resume:false});if(opts.help)console.log('node training/team-search/search.cjs [--meta hybrid|independent|observed] [--usage-file JSON] [--usage-half-life-days N] [--usage-as-of YYYY-MM-DD] [--usage-prior-strength 500] [--hours 6] [--until ISO-TIMESTAMP] [--resume] [--workers N] [--out DIR] [--pool FILE] [--warm-start CHECKPOINT] [--initial-teams 128] [--batch-teams 24] [--opponents 64] [--validation-teams 8] [--validation-opponents 512] [--screen-teams 24] [--screen-opponents 512] [--baseline-count 12] [--candidates 12000] [--epochs 6] [--hidden 16] [--ensemble 12] [--reference-opponents 256] [--fit-fixtures 48000] [--validation-seed N] [--rounds N] [--seed N]');else search(opts).catch(e=>{console.error(e);process.exitCode=1;});}
module.exports={search};
